/**
 * @almadar/ui Tailwind Preset
 *
 * Provides the complete Almadar design token system as a Tailwind preset.
 * Includes a safelist for CSS-variable-based arbitrary classes that use
 * bracket notation (Tailwind can't extract these from source scanning).
 *
 * Note: @almadar/ui dist content scanning is handled by tailwind.config.js
 * in the shell template, not here. The config resolves the dist path via
 * require.resolve('@almadar/ui') which works regardless of hoisting.
 *
 * Usage in tailwind.config.js:
 *   presets: [require('@almadar/ui/tailwind-preset')]
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  safelist: [
  // Standard utilities used via dynamic className from .orb schemas
  'p-4', 'p-6', 'p-8',
  'px-4', 'px-6', 'py-4', 'py-6',
  'mx-auto',
  'w-full',
  'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl', 'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-7xl',
  'min-h-screen',
  'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-6', 'gap-8',
  'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4',
  'sm:grid-cols-2', 'md:grid-cols-2', 'md:grid-cols-3', 'lg:grid-cols-3', 'lg:grid-cols-4',
  'text-center', 'text-left', 'text-right',
  // Non-theme CSS variable classes (no semantic equivalent in theme config)
  'active:scale-[var(--active-scale)]',
  'border-b-[length:var(--border-width)]',
  'border-[length:var(--border-width)]',
  'border-[length:var(--border-width-thin)]',
  'border-l-[length:var(--border-width)]',
  'border-r-[length:var(--border-width)]',
  'border-t-[length:var(--border-width)]',
  'border-x-[length:var(--border-width)]',
  'duration-[var(--transition-fast)]',
  'duration-[var(--transition-normal)]',
  'focus:ring-[length:var(--focus-ring-width)]',
  'focus:ring-offset-[length:var(--focus-ring-offset)]',
  'font-[var(--font-weight-bold)]',
  'font-[var(--font-weight-medium)]',
  'text-[var(--icon-color,currentColor)]',
  'placeholder:text-[var(--color-placeholder)]',
  // Table-specific tokens
  'bg-[var(--color-table-header)]',
  'border-[var(--color-table-border)]',
  'hover:bg-[var(--color-table-row-hover)]',
  'hover:bg-[var(--color-surface-hover)]',
  'hover:border-[var(--color-border-hover)]',
  'hover:border-l-[var(--color-muted)]',
  // Gradient partials with opacity
  'from-[var(--color-primary)]/5',
  'to-[var(--color-secondary)]/5',
  // Opacity variants on semantic colors (used in components)
  'bg-primary/10', 'bg-primary/8', 'bg-accent/10',
  'bg-muted/20', 'bg-muted/30', 'bg-muted/50', 'bg-muted/60',
  'bg-surface/60', 'bg-surface/80',
  'bg-background/10', 'bg-background/80',
  'bg-card/80', 'bg-foreground/0', 'bg-foreground/50',
  'bg-error/10', 'bg-info/10', 'bg-success/10', 'bg-warning/10',
  'border-accent/30', 'border-border/40',
  'border-error/30', 'border-error/50',
  'border-info/30', 'border-success/30', 'border-warning/30',
  'ring-accent/20', 'ring-error/20', 'ring-info/20',
  'ring-muted-foreground/20', 'ring-primary/30',
  'ring-success/20', 'ring-warning/20',
  'text-foreground/30', 'text-foreground/60',
  'text-muted-foreground/50',
  'hover:bg-error/10', 'hover:bg-muted/50', 'hover:bg-muted/80',
  'hover:bg-muted-foreground/15', 'hover:bg-primary/10',
  'dark:bg-foreground/70', 'dark:hover:bg-error/20',
  'group-hover:bg-foreground/20', 'group-hover:text-primary',
  'peer-focus:ring-error/20', 'peer-focus:ring-ring/20',
  // Hover elevation & micro-interactions
  'hover:-translate-y-0.5',
  'hover:-translate-y-1',
  'hover:scale-105',
  'scale-[1.05]',
  'transition-all',
  'duration-200',
  'ring-2',
  'ring-primary',
  
  // Auto-added by audit-tailwind-safelist.ts (2026-03-28)
  'active:scale-[var(--active-scale)]',
  'animate-[combat-flash_0.2s_ease-in-out_2]',
  'animate-[combat-heal-glow_0.8s_ease-in-out]',
  'animate-[combat-pulse-red_0.5s_ease-in-out]',
  'animate-[combat-shake_0.3s_ease-in-out]',
  'animate-[shake_0.3s_ease-in-out]',
  'aspect-[3/4]',
  'bg-[radial-gradient(circle_at_center,rgba(34,197,94,0.2),transparent_70%)]',
  'bg-[radial-gradient(ellipse_at_top,var(--color-primary)/0.08,transparent_60%),',
    'radial-gradient(ellipse_at_bottom_right,var(--color-accent)/0.06,transparent_50%)]',
  'bg-[var(--color-background)]',
  'bg-[var(--color-card)]',
  'bg-[var(--color-table-header)]',
  'bg-accent/10',
  'bg-accent/20',
  'bg-background/80',
  'bg-card/80',
  'bg-error/10',
  'bg-foreground/0',
  'bg-foreground/50',
  'bg-info/10',
  'bg-muted/20',
  'bg-muted/30',
  'bg-muted/50',
  'bg-muted/60',
  'bg-primary/10',
  'bg-primary/20',
  'bg-primary/8',
  'bg-success/10',
  'bg-success/20',
  'bg-surface/60',
  'bg-surface/80',
  'bg-warning/10',
  'border-[length:2px]',
  'border-[length:var(--border-width-thin)]',
  'border-[length:var(--border-width)]',
  'border-[var(--color-border)]',
  'border-[var(--color-table-border)]',
  'border-accent/30',
  'border-b-[length:var(--border-width)]',
  'border-border/40',
  'border-error/30',
  'border-error/50',
  'border-info/30',
  'border-l-[3px]',
  'border-l-[length:var(--border-width)]',
  'border-primary/30',
  'border-r-[length:var(--border-width)]',
  'border-success/30',
  'border-t-[length:var(--border-width)]',
  'border-warning/30',
  'border-x-[length:var(--border-width)]',
  'dark:bg-foreground/70',
  'dark:hover:bg-error/20',
  'data-[active=true]',
  'duration-[var(--transition-fast)]',
  'duration-[var(--transition-normal)]',
  'focus:ring-[length:var(--focus-ring-width)]',
  'focus:ring-offset-[length:var(--focus-ring-offset)]',
  'font-[var(--font-weight-bold)]',
  'font-[var(--font-weight-medium)]',
  'from-[var(--color-primary)]',
  'group-hover:bg-foreground/20',
  'h-[18px]',
  'h-[1em]',
  'h-[80px]',
  'hover:bg-[var(--color-card)]',
  'hover:bg-[var(--color-surface-hover)]',
  'hover:bg-[var(--color-table-row-hover)]',
  'hover:bg-error/10',
  'hover:bg-error/80',
  'hover:bg-muted/50',
  'hover:bg-muted/80',
  'hover:bg-primary/10',
  'hover:border-[var(--color-border-hover)]',
  'hover:border-l-[var(--color-muted)]',
  'left-[-5px]',
  'lg:max-w-[50%]',
  'lg:min-w-[45%]',
  'max-h-[1000px]',
  'max-h-[280px]',
  'max-h-[500px]',
  'max-h-[80vh]',
  'max-w-[120px]',
  'max-w-[160px]',
  'max-w-[180px]',
  'max-w-[200px]',
  'max-w-[280px]',
  'max-w-[300px]',
  'max-w-[400px]',
  'max-w-[60%]',
  'max-w-[75%]',
  'max-w-[80%]',
  'min-h-[200px]',
  'min-h-[240px]',
  'min-h-[24px]',
  'min-h-[2rem]',
  'min-h-[400px]',
  'min-h-[44px]',
  'min-h-[4px]',
  'min-h-[600px]',
  'min-h-[60px]',
  'min-h-[60vh]',
  'min-h-[80px]',
  'min-h-[80vh]',
  'min-w-[100px]',
  'min-w-[120px]',
  'min-w-[130px]',
  'min-w-[140px]',
  'min-w-[160px]',
  'min-w-[18px]',
  'min-w-[2.5rem]',
  'min-w-[200px]',
  'min-w-[20px]',
  'min-w-[2rem]',
  'min-w-[300px]',
  'min-w-[3ch]',
  'min-w-[3rem]',
  'min-w-[40px]',
  'min-w-[44px]',
  'min-w-[60px]',
  'min-w-[65px]',
  'min-w-[800px]',
  'min-w-[80px]',
  'ml-[1px]',
  'ml-[calc(1.5rem)]',
  'peer-focus:ring-error/20',
  'peer-focus:ring-ring/20',
  'placeholder:text-[var(--color-placeholder)]',
  'ring-accent/20',
  'ring-accent/50',
  'ring-error/20',
  'ring-info/20',
  'ring-muted-foreground/20',
  'ring-primary/30',
  'ring-success/20',
  'ring-warning/20',
  'rounded-[var(--radius-md)]',
  'scale-[1.05]',
  'shadow-[0_-4px_6px_-1px_rgb(0,0,0,0.05)]',
  'shadow-[0_0_10px_rgba(251,191,36,0.5)]',
  'shadow-[0_0_6px_rgba(59,130,246,0.3)]',
  'shadow-[0_0_8px_rgba(168,85,247,0.4)]',
  'text-[0.65rem]',
  'text-[10px]',
  'text-[11px]',
  'text-[12px]',
  'text-[13px]',
  'text-[14px]',
  'text-[15px]',
  'text-[8px]',
  'text-[9px]',
  'text-[var(--color-foreground)]',
  'text-[var(--color-muted-foreground)]',
  'text-[var(--icon-color,currentColor)]',
  'text-foreground/30',
  'text-foreground/60',
  'text-foreground/70',
  'text-foreground/80',
  'text-muted-foreground/50',
  'to-[var(--color-secondary)]',
  'w-[280px]',
  'w-[2px]',
  'w-[480px]',
  'w-[640px]',
  'will-change-[opacity,transform]',
  'z-[60]',
],
  theme: {
    fontFamily: {
      // `sans` continues to read --font-family for backward compat.
      sans: ['var(--font-family)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      mono: ['var(--font-family-mono, ui-monospace)', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      // Layer 1 Type axis: display + body family slots fall back to --font-family
      // so existing themes that don't define them keep their current look.
      display: ['var(--font-family-display, var(--font-family))', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      body: ['var(--font-family-body, var(--font-family))', 'ui-sans-serif', 'system-ui', 'sans-serif'],
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          foreground: 'var(--color-primary-foreground)',
          hover: 'var(--color-primary-hover)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          foreground: 'var(--color-secondary-foreground)',
          hover: 'var(--color-secondary-hover)',
        },
        muted: {
          DEFAULT: 'var(--color-muted)',
          foreground: 'var(--color-muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          foreground: 'var(--color-accent-foreground)',
        },
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: {
          DEFAULT: 'var(--color-card)',
          foreground: 'var(--color-card-foreground)',
        },
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        error: {
          DEFAULT: 'var(--color-error)',
          foreground: 'var(--color-error-foreground)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          foreground: 'var(--color-success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          foreground: 'var(--color-warning-foreground)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          foreground: 'var(--color-info-foreground)',
        },
      },
      borderRadius: {
        none: 'var(--radius-none, 0)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
        // Geometry-axis intent overlay. Codemod targets these for `rounded-*` by component intent:
        //   Card / containers   → rounded-container
        //   Button / interactive → rounded-interactive
        //   Avatar / Badge      → rounded-pill
        container: 'var(--radius-container, var(--radius-md))',
        interactive: 'var(--radius-interactive, var(--radius-md))',
        pill: 'var(--radius-pill, var(--radius-full))',
      },
      borderWidth: {
        // Geometry-axis border rhythm with intent. Existing literal `border` / `border-2` keep working.
        hairline: 'var(--border-hairline, 1px)',
        standard: 'var(--border-standard, var(--border-width, 1px))',
        heavy: 'var(--border-heavy, var(--border-width-thick, 2px))',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-main)',
        lg: 'var(--shadow-lg)',
        inner: 'var(--shadow-inner)',
        // Elevation-axis per-layer intent. Codemod targets:
        //   Card                → shadow-elevation-card
        //   Popover / Tooltip   → shadow-elevation-popover
        //   Dialog              → shadow-elevation-dialog
        //   Toast               → shadow-elevation-toast
        'elevation-card': 'var(--elevation-card, var(--shadow-sm))',
        'elevation-popover': 'var(--elevation-popover, var(--shadow-main))',
        'elevation-dialog': 'var(--elevation-dialog, var(--shadow-lg))',
        'elevation-toast': 'var(--elevation-toast, var(--shadow-main))',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal, 400)',
        medium: 'var(--font-weight-medium, 500)',
        bold: 'var(--font-weight-bold, 600)',
      },
      transitionDuration: {
        // Existing aliases retained; resolve through the Motion-axis tokens
        // with the previous `--transition-*` values as fallback so themes that
        // don't define `--duration-*` keep their pre-Layer-1 motion.
        fast: 'var(--duration-fast, var(--transition-fast, 150ms))',
        normal: 'var(--duration-normal, var(--transition-normal, 250ms))',
        slow: 'var(--duration-slow, var(--transition-slow, 400ms))',
        instant: 'var(--duration-instant, 0ms)',
        dramatic: 'var(--duration-dramatic, 600ms)',
      },
      transitionTimingFunction: {
        // Motion-axis easing palette. `standard` falls back to the existing
        // `--transition-timing` so backward compat is preserved.
        linear: 'var(--easing-linear, linear)',
        standard: 'var(--easing-standard, var(--transition-timing, cubic-bezier(0.4, 0, 0.2, 1)))',
        emphasized: 'var(--easing-emphasized, cubic-bezier(0.2, 0, 0, 1))',
        spring: 'var(--easing-spring, cubic-bezier(0.34, 1.56, 0.64, 1))',
      },
      // Density-axis spacing scale. Tailwind's default `p-3` / `gap-4` resolve
      // here so existing classes keep working — but now read from tokens.
      // Defaults match Tailwind's default (12px / 16px / 24px for 3 / 4 / 6),
      // so post-migration visual output is identical until a theme overrides.
      spacing: {
        0: 'var(--space-0, 0px)',
        1: 'var(--space-1, 4px)',
        2: 'var(--space-2, 8px)',
        3: 'var(--space-3, 12px)',
        4: 'var(--space-4, 16px)',
        5: 'var(--space-5, 20px)',
        6: 'var(--space-6, 24px)',
        7: 'var(--space-7, 28px)',
        8: 'var(--space-8, 32px)',
        9: 'var(--space-9, 36px)',
        10: 'var(--space-10, 40px)',
        11: 'var(--space-11, 44px)',
        12: 'var(--space-12, 48px)',
        // Component-intent spacing (codemod targets for padding-by-intent)
        'card-sm': 'var(--card-padding-sm, 12px)',
        'card-md': 'var(--card-padding-md, 16px)',
        'card-lg': 'var(--card-padding-lg, 24px)',
        'dialog': 'var(--dialog-padding, 24px)',
        'section': 'var(--section-gap, 32px)',
      },
      // Type-axis size scale. Each step pairs a size with a line-height,
      // both read from tokens with Tailwind-default fallbacks so existing
      // `text-sm` resolves to the same 14px/20px until a theme overrides.
      fontSize: {
        xs: ['var(--text-xs, 12px)', { lineHeight: 'var(--leading-xs, 16px)' }],
        sm: ['var(--text-sm, 14px)', { lineHeight: 'var(--leading-sm, 20px)' }],
        base: ['var(--text-base, 16px)', { lineHeight: 'var(--leading-base, 24px)' }],
        lg: ['var(--text-lg, 18px)', { lineHeight: 'var(--leading-lg, 28px)' }],
        xl: ['var(--text-xl, 20px)', { lineHeight: 'var(--leading-xl, 28px)' }],
        '2xl': ['var(--text-2xl, 24px)', { lineHeight: 'var(--leading-2xl, 32px)' }],
        '3xl': ['var(--text-3xl, 30px)', { lineHeight: 'var(--leading-3xl, 36px)' }],
        '4xl': ['var(--text-4xl, 36px)', { lineHeight: 'var(--leading-4xl, 40px)' }],
        'display-1': ['var(--text-display-1, 48px)', { lineHeight: 'var(--leading-display-1, 52px)' }],
        'display-2': ['var(--text-display-2, 60px)', { lineHeight: 'var(--leading-display-2, 64px)' }],
      },
      // Density-axis per-element heights (codemod targets for `h-{px}` on
      // buttons / inputs / rows / icons).
      height: {
        'button-sm': 'var(--button-height-sm, 28px)',
        'button-md': 'var(--button-height-md, 36px)',
        'button-lg': 'var(--button-height-lg, 44px)',
        'input-sm': 'var(--input-height-sm, 28px)',
        'input-md': 'var(--input-height-md, 36px)',
        'input-lg': 'var(--input-height-lg, 44px)',
        'row-compact': 'var(--row-height-compact, 32px)',
        'row-normal': 'var(--row-height-normal, 40px)',
        'row-spacious': 'var(--row-height-spacious, 48px)',
        'icon-default': 'var(--icon-default-size, 16px)',
      },
      minHeight: {
        'button-sm': 'var(--button-height-sm, 28px)',
        'button-md': 'var(--button-height-md, 36px)',
        'button-lg': 'var(--button-height-lg, 44px)',
        'input-sm': 'var(--input-height-sm, 28px)',
        'input-md': 'var(--input-height-md, 36px)',
        'input-lg': 'var(--input-height-lg, 44px)',
        'row-compact': 'var(--row-height-compact, 32px)',
        'row-normal': 'var(--row-height-normal, 40px)',
        'row-spacious': 'var(--row-height-spacious, 48px)',
      },
      width: {
        'icon-default': 'var(--icon-default-size, 16px)',
      },
      // Geometry-axis radius rhythm (codemod targets for `rounded-*` by intent).
      // The existing sm/md/lg/xl/full keys above continue to work as-is.
      // Codemod converts `rounded-md` on Card → `rounded-container`, on Button → `rounded-interactive`, on Avatar/Badge → `rounded-pill`.
      // borderRadius is extended below alongside the existing radius tokens.
      // Elevation-axis per-layer shadow mapping.
      // Codemod converts `shadow-sm` on Card → `shadow-elevation-card`, etc.
      // boxShadow is extended below.
      // Container-query breakpoints aligned 1:1 with Tailwind's default
      // viewport breakpoints (sm 640 / md 768 / lg 1024 / xl 1280 /
      // 2xl 1536). Lets components use `@lg/foo:hidden` as a drop-in
      // replacement for `lg:hidden` when they're rendered inside a
      // CSS Container (the Studio preview, embedded iframes, etc.) so
      // the layout responds to the container's width, not the viewport.
      containers: {
        sm: '40rem',
        md: '48rem',
        lg: '64rem',
        xl: '80rem',
        '2xl': '96rem',
      },
    },
  },
};
