/**
 * GENERATED — do not edit by hand. One entry per @almadar/core theme preset
 * (packages/almadar-core/themes/*.json). Regenerate: almadar-sync themes.
 */

import type { UIThemeDefinition } from './ThemeContext';

export const BUILT_IN_THEMES: UIThemeDefinition[] = [
  { name: "almadar", displayName: "Almadar", hasLightMode: true, hasDarkMode: true },
  { name: "almadar-website", displayName: "Almadar Website", hasLightMode: true, hasDarkMode: true },
  { name: "aqua", displayName: "Aqua Gel", hasLightMode: true, hasDarkMode: true },
  { name: "arabesque", displayName: "Arabesque", hasLightMode: true, hasDarkMode: true },
  { name: "art-deco", displayName: "Art Deco 1925", hasLightMode: true, hasDarkMode: true },
  { name: "art-nouveau", displayName: "Art Nouveau", hasLightMode: true, hasDarkMode: true },
  { name: "atelier", displayName: "Atelier", hasLightMode: true, hasDarkMode: true },
  { name: "bauhaus", displayName: "Bauhaus", hasLightMode: true, hasDarkMode: true },
  { name: "bloomberg-dense", displayName: "Bloomberg Dense", hasLightMode: true, hasDarkMode: true },
  { name: "blueprint", displayName: "Blueprint", hasLightMode: true, hasDarkMode: true },
  { name: "clay", displayName: "Clay", hasLightMode: true, hasDarkMode: true },
  { name: "comic", displayName: "Comic Studio", hasLightMode: true, hasDarkMode: true },
  { name: "constructivist", displayName: "Constructivist", hasLightMode: true, hasDarkMode: true },
  { name: "corporate", displayName: "Corporate", hasLightMode: true, hasDarkMode: true },
  { name: "cyberpunk", displayName: "Cyberpunk HUD", hasLightMode: true, hasDarkMode: true },
  { name: "frutiger-aero", displayName: "Frutiger Aero", hasLightMode: true, hasDarkMode: true },
  { name: "game-adventure", displayName: "Game: Adventure", hasLightMode: false, hasDarkMode: true },
  { name: "game-rpg", displayName: "Game: RPG", hasLightMode: false, hasDarkMode: true },
  { name: "game-sci-fi", displayName: "Game: Sci-Fi", hasLightMode: false, hasDarkMode: true },
  { name: "game-ui-pack", displayName: "Game: Flat UI", hasLightMode: false, hasDarkMode: true },
  { name: "gazette", displayName: "Gazette", hasLightMode: true, hasDarkMode: true },
  { name: "glass", displayName: "Glass", hasLightMode: true, hasDarkMode: true },
  { name: "gothic", displayName: "Gothic Manuscript", hasLightMode: true, hasDarkMode: true },
  { name: "ink-wash", displayName: "Ink Wash", hasLightMode: true, hasDarkMode: true },
  { name: "kawaii", displayName: "Kawaii", hasLightMode: true, hasDarkMode: true },
  { name: "kiosk", displayName: "Kiosk", hasLightMode: true, hasDarkMode: true },
  { name: "linear-clean", displayName: "Linear Clean", hasLightMode: true, hasDarkMode: true },
  { name: "luxury", displayName: "Haute Luxe", hasLightMode: true, hasDarkMode: true },
  { name: "mac-classic", displayName: "Classic Mac OS", hasLightMode: true, hasDarkMode: true },
  { name: "material", displayName: "Material 3", hasLightMode: true, hasDarkMode: true },
  { name: "memphis", displayName: "Memphis 80s", hasLightMode: true, hasDarkMode: true },
  { name: "mid-century", displayName: "Mid-Century Modern", hasLightMode: true, hasDarkMode: true },
  { name: "minimalist", displayName: "Minimalist", hasLightMode: true, hasDarkMode: true },
  { name: "mudcloth", displayName: "Mudcloth", hasLightMode: true, hasDarkMode: true },
  { name: "neon", displayName: "Neon", hasLightMode: true, hasDarkMode: true },
  { name: "neumorphic", displayName: "Neumorphic", hasLightMode: true, hasDarkMode: true },
  { name: "newsprint", displayName: "Newsprint", hasLightMode: true, hasDarkMode: true },
  { name: "notion-editorial", displayName: "Notion Editorial", hasLightMode: true, hasDarkMode: true },
  { name: "pixel", displayName: "Pixel Quest", hasLightMode: true, hasDarkMode: true },
  { name: "prism", displayName: "Prism", hasLightMode: true, hasDarkMode: true },
  { name: "retro", displayName: "Retro", hasLightMode: true, hasDarkMode: true },
  { name: "risograph", displayName: "Risograph", hasLightMode: true, hasDarkMode: true },
  { name: "scandi", displayName: "Scandinavian", hasLightMode: true, hasDarkMode: true },
  { name: "sketch", displayName: "Sketchbook", hasLightMode: true, hasDarkMode: true },
  { name: "solarpunk", displayName: "Solarpunk", hasLightMode: true, hasDarkMode: true },
  { name: "steampunk", displayName: "Steampunk", hasLightMode: true, hasDarkMode: true },
  { name: "swiss", displayName: "Swiss International", hasLightMode: true, hasDarkMode: true },
  { name: "terminal", displayName: "Terminal", hasLightMode: true, hasDarkMode: true },
  { name: "trait-wars", displayName: "Trait Wars", hasLightMode: true, hasDarkMode: true },
  { name: "ukiyo-e", displayName: "Ukiyo-e", hasLightMode: true, hasDarkMode: true },
  { name: "vaporwave", displayName: "Vaporwave", hasLightMode: true, hasDarkMode: true },
  { name: "victorian", displayName: "Victorian", hasLightMode: true, hasDarkMode: true },
  { name: "wabi-sabi", displayName: "Wabi-Sabi", hasLightMode: true, hasDarkMode: true },
  { name: "win95", displayName: "Windows 95", hasLightMode: true, hasDarkMode: true },
  { name: "wireframe", displayName: "Wireframe", hasLightMode: true, hasDarkMode: true },
  { name: "zine", displayName: "Punk Zine", hasLightMode: true, hasDarkMode: true },
];
