// AUTO-GENERATED by tools/almadar-pattern-sync/generate-component-registry.ts
// Do not edit manually. Re-run the generator after adding components.
//
// Generated: 2026-05-26T02:09:01.834Z
// Patterns: 304
// Components: 329
// Lazy (Three.js): 1

import React from 'react';

import { AboutPageTemplate } from '../templates/AboutPageTemplate';
import { AccordionPattern, AlertPattern, AvatarPattern, BadgePattern, ButtonPattern, CardPattern, CheckboxPattern, ContainerPattern, FloatButtonPattern, HeadingPattern, IconButtonPattern, IconPattern, ImagePattern, InputPattern, LabelPattern, LinkPattern, MapViewPattern, MenuPattern, PopoverPattern, ProgressBarPattern, RadioPattern, SelectPattern, SimpleGridPattern, SpinnerPattern, TextPattern, TextareaPattern, TooltipPattern } from './ComponentPatterns';
import { ActionButton } from '../atoms/game/ActionButton';
import { ActionButtons } from '../molecules/game/ActionButtons';
import { ActionPalette } from './game/puzzles/sequencer/ActionPalette';
import { ActionTile } from './game/puzzles/sequencer/ActionTile';
import { AnimatedCounter } from '../atoms/AnimatedCounter';
import { AnimatedGraphic } from '../atoms/AnimatedGraphic';
import { AnimatedReveal } from '../atoms/AnimatedReveal';
import { ArticleSection } from '../molecules/ArticleSection';
import { Aside } from '../atoms/Aside';
import { AuthLayout } from '../templates/AuthLayout';
import { BattleBoard } from './game/BattleBoard';
import { BattleTemplate } from '../templates/BattleTemplate';
import { BehaviorView } from '../molecules/avl/BehaviorView';
import { BookChapterView } from './book/BookChapterView';
import { BookCoverPage } from './book/BookCoverPage';
import { BookNavBar } from './book/BookNavBar';
import { BookTableOfContents } from './book/BookTableOfContents';
import { BookViewer } from './book/BookViewer';
import { BoxPattern, CenterPattern, DividerPattern, GridPattern, HStackPattern, SpacerPattern, VStackPattern } from './LayoutPatterns';
import { BranchingLogicBuilder } from '../molecules/BranchingLogicBuilder';
import { Breadcrumb } from '../molecules/Breadcrumb';
import { BuilderBoard } from './game/puzzles/builder/BuilderBoard';
import { ButtonGroup } from '../molecules/ButtonGroup';
import { CTABanner } from '../molecules/CTABanner';
import { CalendarGrid } from '../molecules/CalendarGrid';
import { CanvasEffect } from './game/CanvasEffect';
import { CardGrid } from './CardGrid';
import { Carousel } from '../molecules/Carousel';
import { CaseStudyCard } from '../molecules/CaseStudyCard';
import { CaseStudyOrganism } from './CaseStudyOrganism';
import { CastleBoard } from './game/CastleBoard';
import { CastleTemplate } from '../templates/CastleTemplate';
import { Chart } from './Chart';
import { ChartLegend } from '../molecules/ChartLegend';
import { ChoiceButton } from '../atoms/game/ChoiceButton';
import { ClassifierBoard } from './game/puzzles/classifier/ClassifierBoard';
import { CodeBlock } from '../molecules/markdown/CodeBlock';
import { CodeExample } from '../molecules/CodeExample';
import { CodeView } from './game/puzzles/state-architect/CodeView';
import { CodeViewer } from './CodeViewer';
import { CombatLog } from '../molecules/game/CombatLog';
import { ComboCounter } from '../atoms/game/ComboCounter';
import { CommunityLinks } from '../molecules/CommunityLinks';
import { ConditionalWrapper } from '../atoms/ConditionalWrapper';
import { ConfettiEffect } from '../atoms/ConfettiEffect';
import { ConfirmDialog } from './ConfirmDialog';
import { ContentRenderer } from './ContentRenderer';
import { ContentSection } from '../atoms/ContentSection';
import { ControlButton } from '../atoms/game/ControlButton';
import { CounterTemplate } from '../templates/CounterTemplate';
import { CraftingRecipe } from '../molecules/game/CraftingRecipe';
import { CustomPattern } from './CustomPattern';
import { DPad } from '../molecules/game/DPad';
import { DamageNumber } from '../atoms/game/DamageNumber';
import { DashboardGrid } from './layout/DashboardGrid';
import { DashboardLayout } from '../templates/DashboardLayout';
import { DataGrid } from '../molecules/DataGrid';
import { DataList } from '../molecules/DataList';
import { DataTable } from './DataTable';
import { DateRangePicker } from '../molecules/DateRangePicker';
import { DateRangeSelector } from '../molecules/DateRangeSelector';
import { DayCell } from '../atoms/DayCell';
import { DebuggerBoard } from './game/puzzles/debugger/DebuggerBoard';
import { DetailPanel } from './DetailPanel';
import { Dialog } from '../atoms/Dialog';
import { DialogueBox } from '../molecules/game/DialogueBox';
import { DialogueBubble } from '../atoms/game/DialogueBubble';
import { DocBreadcrumb } from '../molecules/DocBreadcrumb';
import { DocCodeBlock } from '../molecules/DocCodeBlock';
import { DocPagination } from '../molecules/DocPagination';
import { DocSearch } from '../molecules/DocSearch';
import { DocSidebar } from '../molecules/DocSidebar';
import { DocTOC } from '../molecules/DocTOC';
import { DocumentViewer } from './DocumentViewer';
import { Drawer } from '../molecules/Drawer';
import { DrawerSlot } from './DrawerSlot';
import { EdgeDecoration } from '../molecules/EdgeDecoration';
import { EmptyState } from '../molecules/EmptyState';
import { EnemyPlate } from '../molecules/game/EnemyPlate';
import { ErrorBoundary } from '../molecules/ErrorBoundary';
import { ErrorState } from '../molecules/ErrorState';
import { EventHandlerBoard } from './game/puzzles/event-handler/EventHandlerBoard';
import { EventLog } from './game/puzzles/event-handler/EventLog';
import { FeatureCard } from '../molecules/FeatureCard';
import { FeatureDetailPageTemplate } from '../templates/FeatureDetailPageTemplate';
import { FeatureGrid } from '../molecules/FeatureGrid';
import { FeatureGridOrganism } from './FeatureGridOrganism';
import { FileTree } from '../molecules/FileTree';
import { FilterGroup } from '../molecules/FilterGroup';
import { FilterPill } from '../atoms/FilterPill';
import { Flex } from '../molecules/Flex';
import { FlipCard } from '../molecules/FlipCard';
import { FlipContainer } from '../atoms/FlipContainer';
import { FloatingActionButton } from '../molecules/FloatingActionButton';
import { Form } from './Form';
import { FormField } from '../molecules/FormField';
import { FormSectionHeader } from '../molecules/FormSectionHeader';
import { GameAudioProvider } from './game/GameAudioProvider';
import { GameAudioToggle } from './game/GameAudioToggle';
import { GameCanvas2D } from '../molecules/game/GameCanvas2D';
import { GameHud } from '../molecules/game/GameHud';
import { GameMenu } from '../molecules/game/GameMenu';
import { GameOverScreen } from '../molecules/game/GameOverScreen';
import { GameShell } from '../templates/GameShell';
import { GameTemplate } from '../templates/GameTemplate';
import { GenericAppTemplate } from '../templates/GenericAppTemplate';
import { GeometricPattern } from '../molecules/GeometricPattern';
import { GradientDivider } from '../molecules/GradientDivider';
import { GraphCanvas } from './GraphCanvas';
import { GraphView } from '../molecules/GraphView';
import { Header } from './Header';
import { HealthBar } from '../atoms/game/HealthBar';
import { HealthPanel } from '../molecules/game/HealthPanel';
import { HeroOrganism } from './HeroOrganism';
import { HeroSection } from '../molecules/HeroSection';
import { InfiniteScrollSentinel } from '../atoms/InfiniteScrollSentinel';
import { InputGroup } from '../molecules/InputGroup';
import { InstallBox } from '../molecules/InstallBox';
import { InventoryGrid } from '../molecules/game/InventoryGrid';
import { InventoryPanel } from '../molecules/game/InventoryPanel';
import { IsometricCanvas } from '../molecules/game/IsometricCanvas';
import { ItemSlot } from '../atoms/game/ItemSlot';
import { JazariStateMachine } from './JazariStateMachine';
import { LandingPageTemplate } from '../templates/LandingPageTemplate';
import { LawReferenceTooltip } from '../atoms/LawReferenceTooltip';
import { Lightbox } from '../molecules/Lightbox';
import { LikertScale } from '../molecules/LikertScale';
import { LineChart } from '../molecules/LineChart';
import { List } from './List';
import { LoadingState } from '../molecules/LoadingState';
import { MarkdownContent } from '../molecules/markdown/MarkdownContent';
import { MarketingFooter } from '../molecules/MarketingFooter';
import { MasterDetail } from './MasterDetail';
import { MasterDetailLayout } from './layout/MasterDetailLayout';
import { MatrixQuestion } from '../molecules/MatrixQuestion';
import { MediaGallery } from './MediaGallery';
import { Meter } from '../molecules/Meter';
import { MiniMap } from '../atoms/game/MiniMap';
import { Modal } from '../molecules/Modal';
import { ModalSlot } from './ModalSlot';
import { ModuleCard } from '../molecules/avl/ModuleCard';
import { Navigation } from './Navigation';
import { NegotiatorBoard } from './game/puzzles/negotiator/NegotiatorBoard';
import { NumberStepper } from '../molecules/NumberStepper';
import { ObjectRulePanel } from './game/puzzles/event-handler/ObjectRulePanel';
import { OptionConstraintGroup } from '../molecules/OptionConstraintGroup';
import { OrbitalVisualization } from './OrbitalVisualization';
import { Overlay } from '../atoms/Overlay';
import { PageHeader } from './PageHeader';
import { Pagination } from '../molecules/Pagination';
import { PatternTile } from '../atoms/PatternTile';
import { PlatformerCanvas } from '../molecules/game/PlatformerCanvas';
import { PositionedCanvas } from '../molecules/PositionedCanvas';
import { PowerupSlots } from '../molecules/game/PowerupSlots';
import { PricingCard } from '../molecules/PricingCard';
import { PricingGrid } from '../molecules/PricingGrid';
import { PricingOrganism } from './PricingOrganism';
import { PricingPageTemplate } from '../templates/PricingPageTemplate';
import { ProgressDots } from '../molecules/ProgressDots';
import { PullQuote } from '../molecules/PullQuote';
import { PullToRefresh } from '../molecules/PullToRefresh';
import { QrScanner } from '../molecules/QrScanner';
import { QuestTracker } from '../molecules/game/QuestTracker';
import { QuizBlock } from '../molecules/QuizBlock';
import { RangeSlider } from '../atoms/RangeSlider';
import { RelationSelect } from '../molecules/RelationSelect';
import { RepeatableFormSection } from '../molecules/RepeatableFormSection';
import { ReplyTree } from '../molecules/ReplyTree';
import { ResourceBar } from '../molecules/game/ResourceBar';
import { ResourceCounter } from '../atoms/game/ResourceCounter';
import { RichBlockEditor } from '../molecules/RichBlockEditor';
import { RuleEditor } from './game/puzzles/event-handler/RuleEditor';
import { RuntimeDebugger } from './debug/RuntimeDebugger';
import { ScaledDiagram } from '../molecules/ScaledDiagram';
import { ScoreBoard } from '../molecules/game/ScoreBoard';
import { ScoreDisplay } from '../atoms/game/ScoreDisplay';
import { SearchInput } from '../molecules/SearchInput';
import { Section } from './Section';
import { SectionHeader } from '../atoms/SectionHeader';
import { SequenceBar } from './game/puzzles/sequencer/SequenceBar';
import { SequencerBoard } from './game/puzzles/sequencer/SequencerBoard';
import { ServiceCatalog } from '../molecules/ServiceCatalog';
import { ShowcaseCard } from '../molecules/ShowcaseCard';
import { ShowcaseOrganism } from './ShowcaseOrganism';
import { SidePanel } from '../molecules/SidePanel';
import { Sidebar } from './Sidebar';
import { SignaturePad } from './SignaturePad';
import { SimulationCanvas } from './game/physics-sim/SimulationCanvas';
import { SimulationControls } from './game/physics-sim/SimulationControls';
import { SimulationGraph } from './game/physics-sim/SimulationGraph';
import { SimulatorBoard } from './game/puzzles/simulator/SimulatorBoard';
import { Skeleton } from '../molecules/Skeleton';
import { SocialProof } from '../molecules/SocialProof';
import { SortableList } from '../molecules/SortableList';
import { Sparkline } from '../atoms/Sparkline';
import { Split } from './Split';
import { SplitPane } from './layout/SplitPane';
import { SplitSection } from '../molecules/SplitSection';
import { Sprite } from '../atoms/game/Sprite';
import { Stack } from '../atoms/Stack';
import { StarRating } from '../molecules/StarRating';
import { StatBadge } from '../molecules/game/StatBadge';
import { StatCard } from './StatCard';
import { StatDisplay } from '../molecules/StatDisplay';
import { StateArchitectBoard } from './game/puzzles/state-architect/StateArchitectBoard';
import { StateIndicator } from '../atoms/game/StateIndicator';
import { StateMachineView } from './StateMachineView';
import { StateNode } from './game/puzzles/state-architect/StateNode';
import { StatsGrid } from '../molecules/StatsGrid';
import { StatsOrganism } from './StatsOrganism';
import { StatusDot } from '../atoms/StatusDot';
import { StatusEffect } from '../atoms/game/StatusEffect';
import { StepFlowOrganism } from './StepFlowOrganism';
import { SvgBranch } from '../atoms/svg/SvgBranch';
import { SvgConnection } from '../atoms/svg/SvgConnection';
import { SvgFlow } from '../atoms/svg/SvgFlow';
import { SvgGrid } from '../atoms/svg/SvgGrid';
import { SvgLobe } from '../atoms/svg/SvgLobe';
import { SvgMesh } from '../atoms/svg/SvgMesh';
import { SvgMorph } from '../atoms/svg/SvgMorph';
import { SvgNode } from '../atoms/svg/SvgNode';
import { SvgPulse } from '../atoms/svg/SvgPulse';
import { SvgRing } from '../atoms/svg/SvgRing';
import { SvgShield } from '../atoms/svg/SvgShield';
import { SvgStack } from '../atoms/svg/SvgStack';
import { SwipeableRow } from '../molecules/SwipeableRow';
import { Switch } from '../atoms/Switch';
import { TabbedContainer } from './layout/TabbedContainer';
import { Table } from './Table';
import { Tabs } from '../molecules/Tabs';
import { TagCloud } from '../molecules/TagCloud';
import { TagInput } from '../molecules/TagInput';
import { TeamCard } from '../molecules/TeamCard';
import { TeamOrganism } from './TeamOrganism';
import { TextHighlight } from '../atoms/TextHighlight';
import { ThemeToggle } from '../atoms/ThemeToggle';
import { TimeSlotCell } from '../atoms/TimeSlotCell';
import { Timeline } from './Timeline';
import { TimerDisplay } from '../atoms/game/TimerDisplay';
import { Toast } from '../molecules/Toast';
import { ToastSlot } from './ToastSlot';
import { TraitFrame } from '../atoms/TraitFrame';
import { TraitSlot } from './game/TraitSlot';
import { TraitStateViewer } from './game/TraitStateViewer';
import { TransitionArrow } from './game/puzzles/state-architect/TransitionArrow';
import { TrendIndicator } from '../atoms/TrendIndicator';
import { TurnIndicator } from '../atoms/game/TurnIndicator';
import { TurnPanel } from '../molecules/game/TurnPanel';
import { TypewriterText } from '../atoms/TypewriterText';
import { Typography } from '../atoms/Typography';
import { UISlotRenderer } from './UISlotRenderer';
import { UncontrolledBattleBoard } from './game/UncontrolledBattleBoard';
import { UnitCommandBar } from '../molecules/game/UnitCommandBar';
import { UploadDropZone } from '../molecules/UploadDropZone';
import { VariablePanel } from './game/puzzles/state-architect/VariablePanel';
import { VersionDiff } from '../molecules/VersionDiff';
import { ViolationAlert } from '../molecules/ViolationAlert';
import { VoteStack } from '../molecules/VoteStack';
import { WaypointMarker } from '../atoms/game/WaypointMarker';
import { WizardContainer } from './WizardContainer';
import { WizardNavigation } from '../molecules/WizardNavigation';
import { WizardProgress } from '../molecules/WizardProgress';
import { WorldMapBoard } from './game/WorldMapBoard';
import { WorldMapTemplate } from '../templates/WorldMapTemplate';
import { XPBar } from '../atoms/game/XPBar';

// ---------------------------------------------------------------------------
// Three.js components — lazy-loaded to avoid pulling @react-three/fiber into
// the main bundle. Each wrapper includes its own Suspense boundary so callers
// don't need to wrap them.
// ---------------------------------------------------------------------------
type AnyComponent = React.ComponentType<Record<string, unknown>>;

function lazyThree(
  name: string,
  loader: () => Promise<Record<string, unknown>>,
): AnyComponent {
  const Lazy = React.lazy(() => loader().then(m => ({ default: m[name] as unknown as AnyComponent })));
  function ThreeWrapper(props: Record<string, unknown>) {
    return React.createElement(
      React.Suspense,
      { fallback: null },
      React.createElement(Lazy, props),
    );
  }
  ThreeWrapper.displayName = `Lazy(${name})`;
  return ThreeWrapper;
}

const FeatureRenderer = lazyThree('FeatureRenderer', () => import('@almadar/ui/components/organisms/game/three'));

/**
 * Maps component names to actual React components.
 * Generated from @almadar/patterns component-mapping.json.
 *
 * Pattern wrappers (ButtonPattern, VStackPattern, etc.) adapt the raw component
 * API to the render-ui config format. Direct components are used when no wrapper exists.
 */
export const COMPONENT_REGISTRY: Record<string, React.ComponentType<any>> = {
  'AboutPageTemplate': AboutPageTemplate,
  'Accordion': AccordionPattern,
  'AccordionPattern': AccordionPattern,
  'ActionButton': ActionButton,
  'ActionButtons': ActionButtons,
  'ActionPalette': ActionPalette,
  'ActionTile': ActionTile,
  'Alert': AlertPattern,
  'AlertPattern': AlertPattern,
  'AnimatedCounter': AnimatedCounter,
  'AnimatedGraphic': AnimatedGraphic,
  'AnimatedReveal': AnimatedReveal,
  'ArticleSection': ArticleSection,
  'Aside': Aside,
  'AuthLayout': AuthLayout,
  'Avatar': AvatarPattern,
  'AvatarPattern': AvatarPattern,
  'Badge': BadgePattern,
  'BadgePattern': BadgePattern,
  'BattleBoard': BattleBoard,
  'BattleTemplate': BattleTemplate,
  'BehaviorView': BehaviorView,
  'BookChapterView': BookChapterView,
  'BookCoverPage': BookCoverPage,
  'BookNavBar': BookNavBar,
  'BookTableOfContents': BookTableOfContents,
  'BookViewer': BookViewer,
  'Box': BoxPattern,
  'BoxPattern': BoxPattern,
  'BranchingLogicBuilder': BranchingLogicBuilder,
  'Breadcrumb': Breadcrumb,
  'BuilderBoard': BuilderBoard,
  'Button': ButtonPattern,
  'ButtonGroup': ButtonGroup,
  'ButtonPattern': ButtonPattern,
  'CTABanner': CTABanner,
  'CalendarGrid': CalendarGrid,
  'CanvasEffect': CanvasEffect,
  'Card': CardPattern,
  'CardGrid': CardGrid,
  'CardPattern': CardPattern,
  'Carousel': Carousel,
  'CaseStudyCard': CaseStudyCard,
  'CaseStudyOrganism': CaseStudyOrganism,
  'CastleBoard': CastleBoard,
  'CastleTemplate': CastleTemplate,
  'Center': CenterPattern,
  'CenterPattern': CenterPattern,
  'Chart': Chart,
  'ChartLegend': ChartLegend,
  'Checkbox': CheckboxPattern,
  'CheckboxPattern': CheckboxPattern,
  'ChoiceButton': ChoiceButton,
  'ClassifierBoard': ClassifierBoard,
  'CodeBlock': CodeBlock,
  'CodeExample': CodeExample,
  'CodeView': CodeView,
  'CodeViewer': CodeViewer,
  'CombatLog': CombatLog,
  'ComboCounter': ComboCounter,
  'CommunityLinks': CommunityLinks,
  'ConditionalWrapper': ConditionalWrapper,
  'ConfettiEffect': ConfettiEffect,
  'ConfirmDialog': ConfirmDialog,
  'Container': ContainerPattern,
  'ContainerPattern': ContainerPattern,
  'ContentRenderer': ContentRenderer,
  'ContentSection': ContentSection,
  'ControlButton': ControlButton,
  'CounterTemplate': CounterTemplate,
  'CraftingRecipe': CraftingRecipe,
  'DPad': DPad,
  'DamageNumber': DamageNumber,
  'DashboardGrid': DashboardGrid,
  'DashboardLayout': DashboardLayout,
  'DataGrid': DataGrid,
  'DataList': DataList,
  'DataTable': DataTable,
  'DateRangePicker': DateRangePicker,
  'DateRangeSelector': DateRangeSelector,
  'DayCell': DayCell,
  'DebuggerBoard': DebuggerBoard,
  'DetailPanel': DetailPanel,
  'Dialog': Dialog,
  'DialogueBox': DialogueBox,
  'DialogueBubble': DialogueBubble,
  'Divider': DividerPattern,
  'DividerPattern': DividerPattern,
  'DocBreadcrumb': DocBreadcrumb,
  'DocCodeBlock': DocCodeBlock,
  'DocPagination': DocPagination,
  'DocSearch': DocSearch,
  'DocSidebar': DocSidebar,
  'DocTOC': DocTOC,
  'DocumentViewer': DocumentViewer,
  'Drawer': Drawer,
  'DrawerSlot': DrawerSlot,
  'EdgeDecoration': EdgeDecoration,
  'EmptyState': EmptyState,
  'EnemyPlate': EnemyPlate,
  'ErrorBoundary': ErrorBoundary,
  'ErrorState': ErrorState,
  'EventHandlerBoard': EventHandlerBoard,
  'EventLog': EventLog,
  'FeatureCard': FeatureCard,
  'FeatureDetailPageTemplate': FeatureDetailPageTemplate,
  'FeatureGrid': FeatureGrid,
  'FeatureGridOrganism': FeatureGridOrganism,
  'FeatureRenderer': FeatureRenderer,
  'FileTree': FileTree,
  'FilterGroup': FilterGroup,
  'FilterPill': FilterPill,
  'Flex': Flex,
  'FlipCard': FlipCard,
  'FlipContainer': FlipContainer,
  'FloatingActionButton': FloatingActionButton,
  'Form': Form,
  'FormField': FormField,
  'FormSectionHeader': FormSectionHeader,
  'GameAudioProvider': GameAudioProvider,
  'GameAudioToggle': GameAudioToggle,
  'GameCanvas2D': GameCanvas2D,
  'GameHud': GameHud,
  'GameMenu': GameMenu,
  'GameOverScreen': GameOverScreen,
  'GameShell': GameShell,
  'GameTemplate': GameTemplate,
  'GenericAppTemplate': GenericAppTemplate,
  'GeometricPattern': GeometricPattern,
  'GradientDivider': GradientDivider,
  'GraphCanvas': GraphCanvas,
  'GraphView': GraphView,
  'Grid': GridPattern,
  'GridPattern': GridPattern,
  'HStack': HStackPattern,
  'HStackPattern': HStackPattern,
  'Header': Header,
  'HealthBar': HealthBar,
  'HealthPanel': HealthPanel,
  'HeroOrganism': HeroOrganism,
  'HeroSection': HeroSection,
  'Icon': IconPattern,
  'IconPattern': IconPattern,
  'InfiniteScrollSentinel': InfiniteScrollSentinel,
  'Input': InputPattern,
  'InputGroup': InputGroup,
  'InputPattern': InputPattern,
  'InstallBox': InstallBox,
  'InventoryGrid': InventoryGrid,
  'InventoryPanel': InventoryPanel,
  'IsometricCanvas': IsometricCanvas,
  'ItemSlot': ItemSlot,
  'JazariStateMachine': JazariStateMachine,
  'Label': LabelPattern,
  'LabelPattern': LabelPattern,
  'LandingPageTemplate': LandingPageTemplate,
  'LawReferenceTooltip': LawReferenceTooltip,
  'Lightbox': Lightbox,
  'LikertScale': LikertScale,
  'LineChart': LineChart,
  'List': List,
  'LoadingState': LoadingState,
  'MapView': MapViewPattern,
  'MapViewPattern': MapViewPattern,
  'MarkdownContent': MarkdownContent,
  'MarketingFooter': MarketingFooter,
  'MasterDetail': MasterDetail,
  'MasterDetailLayout': MasterDetailLayout,
  'MatrixQuestion': MatrixQuestion,
  'MediaGallery': MediaGallery,
  'Menu': MenuPattern,
  'MenuPattern': MenuPattern,
  'Meter': Meter,
  'MiniMap': MiniMap,
  'Modal': Modal,
  'ModalSlot': ModalSlot,
  'ModuleCard': ModuleCard,
  'Navigation': Navigation,
  'NegotiatorBoard': NegotiatorBoard,
  'NumberStepper': NumberStepper,
  'ObjectRulePanel': ObjectRulePanel,
  'OptionConstraintGroup': OptionConstraintGroup,
  'OrbitalVisualization': OrbitalVisualization,
  'Overlay': Overlay,
  'PageHeader': PageHeader,
  'Pagination': Pagination,
  'PatternTile': PatternTile,
  'PlatformerCanvas': PlatformerCanvas,
  'Popover': PopoverPattern,
  'PopoverPattern': PopoverPattern,
  'PositionedCanvas': PositionedCanvas,
  'PowerupSlots': PowerupSlots,
  'PricingCard': PricingCard,
  'PricingGrid': PricingGrid,
  'PricingOrganism': PricingOrganism,
  'PricingPageTemplate': PricingPageTemplate,
  'ProgressBar': ProgressBarPattern,
  'ProgressBarPattern': ProgressBarPattern,
  'ProgressDots': ProgressDots,
  'PullQuote': PullQuote,
  'PullToRefresh': PullToRefresh,
  'QrScanner': QrScanner,
  'QuestTracker': QuestTracker,
  'QuizBlock': QuizBlock,
  'Radio': RadioPattern,
  'RadioPattern': RadioPattern,
  'RangeSlider': RangeSlider,
  'RelationSelect': RelationSelect,
  'RepeatableFormSection': RepeatableFormSection,
  'ReplyTree': ReplyTree,
  'ResourceBar': ResourceBar,
  'ResourceCounter': ResourceCounter,
  'RichBlockEditor': RichBlockEditor,
  'RuleEditor': RuleEditor,
  'RuntimeDebugger': RuntimeDebugger,
  'ScaledDiagram': ScaledDiagram,
  'ScoreBoard': ScoreBoard,
  'ScoreDisplay': ScoreDisplay,
  'SearchInput': SearchInput,
  'Section': Section,
  'SectionHeader': SectionHeader,
  'Select': SelectPattern,
  'SelectPattern': SelectPattern,
  'SequenceBar': SequenceBar,
  'SequencerBoard': SequencerBoard,
  'ServiceCatalog': ServiceCatalog,
  'ShowcaseCard': ShowcaseCard,
  'ShowcaseOrganism': ShowcaseOrganism,
  'SidePanel': SidePanel,
  'Sidebar': Sidebar,
  'SignaturePad': SignaturePad,
  'SimpleGrid': SimpleGridPattern,
  'SimpleGridPattern': SimpleGridPattern,
  'SimulationCanvas': SimulationCanvas,
  'SimulationControls': SimulationControls,
  'SimulationGraph': SimulationGraph,
  'SimulatorBoard': SimulatorBoard,
  'Skeleton': Skeleton,
  'SocialProof': SocialProof,
  'SortableList': SortableList,
  'Spacer': SpacerPattern,
  'SpacerPattern': SpacerPattern,
  'Sparkline': Sparkline,
  'Spinner': SpinnerPattern,
  'SpinnerPattern': SpinnerPattern,
  'Split': Split,
  'SplitPane': SplitPane,
  'SplitSection': SplitSection,
  'Sprite': Sprite,
  'Stack': Stack,
  'StarRating': StarRating,
  'StatBadge': StatBadge,
  'StatCard': StatCard,
  'StatDisplay': StatDisplay,
  'StateArchitectBoard': StateArchitectBoard,
  'StateIndicator': StateIndicator,
  'StateMachineView': StateMachineView,
  'StateNode': StateNode,
  'StatsGrid': StatsGrid,
  'StatsOrganism': StatsOrganism,
  'StatusDot': StatusDot,
  'StatusEffect': StatusEffect,
  'StepFlowOrganism': StepFlowOrganism,
  'SvgBranch': SvgBranch,
  'SvgConnection': SvgConnection,
  'SvgFlow': SvgFlow,
  'SvgGrid': SvgGrid,
  'SvgLobe': SvgLobe,
  'SvgMesh': SvgMesh,
  'SvgMorph': SvgMorph,
  'SvgNode': SvgNode,
  'SvgPulse': SvgPulse,
  'SvgRing': SvgRing,
  'SvgShield': SvgShield,
  'SvgStack': SvgStack,
  'SwipeableRow': SwipeableRow,
  'Switch': Switch,
  'TabbedContainer': TabbedContainer,
  'Table': Table,
  'Tabs': Tabs,
  'TagCloud': TagCloud,
  'TagInput': TagInput,
  'TeamCard': TeamCard,
  'TeamOrganism': TeamOrganism,
  'TextHighlight': TextHighlight,
  'Textarea': TextareaPattern,
  'TextareaPattern': TextareaPattern,
  'ThemeToggle': ThemeToggle,
  'TimeSlotCell': TimeSlotCell,
  'Timeline': Timeline,
  'TimerDisplay': TimerDisplay,
  'Toast': Toast,
  'ToastSlot': ToastSlot,
  'Tooltip': TooltipPattern,
  'TooltipPattern': TooltipPattern,
  'TraitFrame': TraitFrame,
  'TraitSlot': TraitSlot,
  'TraitStateViewer': TraitStateViewer,
  'TransitionArrow': TransitionArrow,
  'TrendIndicator': TrendIndicator,
  'TurnIndicator': TurnIndicator,
  'TurnPanel': TurnPanel,
  'TypewriterText': TypewriterText,
  'Typography': Typography,
  'UISlotRenderer': UISlotRenderer,
  'UncontrolledBattleBoard': UncontrolledBattleBoard,
  'UnitCommandBar': UnitCommandBar,
  'UploadDropZone': UploadDropZone,
  'VStack': VStackPattern,
  'VStackPattern': VStackPattern,
  'VariablePanel': VariablePanel,
  'VersionDiff': VersionDiff,
  'ViolationAlert': ViolationAlert,
  'VoteStack': VoteStack,
  'WaypointMarker': WaypointMarker,
  'WizardContainer': WizardContainer,
  'WizardNavigation': WizardNavigation,
  'WizardProgress': WizardProgress,
  'WorldMapBoard': WorldMapBoard,
  'WorldMapTemplate': WorldMapTemplate,
  'XPBar': XPBar,

  // Semantic aliases
  'Text': TextPattern,
};
