// AUTO-GENERATED by tools/almadar-pattern-sync/generate-component-registry.ts
// Do not edit manually. Re-run the generator after adding components.
//
// Generated: 2026-03-22T01:01:22.777Z
// Patterns: 242
// Components: 266
// Lazy (Three.js): 15

import React from 'react';

import { AccordionPattern, AlertPattern, AvatarPattern, BadgePattern, ButtonPattern, CardPattern, CheckboxPattern, ContainerPattern, FloatButtonPattern, HeadingPattern, IconButtonPattern, IconPattern, ImagePattern, InputPattern, LabelPattern, LinkPattern, MapViewPattern, MenuPattern, PopoverPattern, ProgressBarPattern, RadioPattern, SelectPattern, SimpleGridPattern, SpinnerPattern, TextPattern, TextareaPattern, TooltipPattern } from './ComponentPatterns';
import { ActionButton } from '../atoms/game/ActionButton';
import { ActionButtons } from '../molecules/game/ActionButtons';
import { ActionPalette } from './game/puzzles/sequencer/ActionPalette';
import { ActionTile } from './game/puzzles/sequencer/ActionTile';
import { AnimatedCounter } from '../atoms/AnimatedCounter';
import { AuthLayout } from '../templates/AuthLayout';
import { BattleBoard } from './game/BattleBoard';
import { BattleTemplate } from '../templates/BattleTemplate';
import { BookChapterView } from './book/BookChapterView';
import { BookCoverPage } from './book/BookCoverPage';
import { BookNavBar } from './book/BookNavBar';
import { BookTableOfContents } from './book/BookTableOfContents';
import { BookViewer } from './book/BookViewer';
import { BoxPattern, CenterPattern, DividerPattern, GridPattern, HStackPattern, SpacerPattern, VStackPattern } from './LayoutPatterns';
import { Breadcrumb } from '../molecules/Breadcrumb';
import { BuilderBoard } from './game/puzzles/builder/BuilderBoard';
import { ButtonGroup } from '../molecules/ButtonGroup';
import { CalendarGrid } from '../molecules/CalendarGrid';
import { CanvasEffect } from './game/CanvasEffect';
import { CardGrid } from './CardGrid';
import { Carousel } from '../molecules/Carousel';
import { CastleBoard } from './game/CastleBoard';
import { CastleTemplate } from '../templates/CastleTemplate';
import { Chart } from './Chart';
import { ChartLegend } from '../molecules/ChartLegend';
import { ChoiceButton } from '../atoms/game/ChoiceButton';
import { ClassifierBoard } from './game/puzzles/classifier/ClassifierBoard';
import { CodeBlock } from '../molecules/markdown/CodeBlock';
import { CodeView } from './game/puzzles/state-architect/CodeView';
import { CodeViewer } from './CodeViewer';
import { CombatLog } from '../molecules/game/CombatLog';
import { ComboCounter } from '../atoms/game/ComboCounter';
import { ConditionalWrapper } from '../atoms/ConditionalWrapper';
import { ConfettiEffect } from '../atoms/ConfettiEffect';
import { ConfirmDialog } from './ConfirmDialog';
import { ContentRenderer } from './ContentRenderer';
import { ControlButton } from '../atoms/game/ControlButton';
import { CounterTemplate } from '../templates/CounterTemplate';
import { CraftingRecipe } from '../molecules/game/CraftingRecipe';
import { CustomPattern } from './CustomPattern';
import { DPad } from '../molecules/game/DPad';
import { DamageNumber } from '../atoms/game/DamageNumber';
import { DashboardGrid } from './layout/DashboardGrid';
import { DashboardLayout } from '../templates/DashboardLayout';
import { DataGrid } from '../molecules/DataGrid';
import { DataList } from '../molecules/DataList';
import { DataTable } from './DataTable';
import { DateRangeSelector } from '../molecules/DateRangeSelector';
import { DayCell } from '../atoms/DayCell';
import { DebuggerBoard } from './game/puzzles/debugger/DebuggerBoard';
import { DetailPanel } from './DetailPanel';
import { DialogueBox } from './game/DialogueBox';
import { DialogueBubble } from '../atoms/game/DialogueBubble';
import { DocumentViewer } from './DocumentViewer';
import { Drawer } from '../molecules/Drawer';
import { DrawerSlot } from './DrawerSlot';
import { EmptyState } from '../molecules/EmptyState';
import { EnemyPlate } from '../molecules/game/EnemyPlate';
import { ErrorBoundary } from '../molecules/ErrorBoundary';
import { ErrorState } from '../molecules/ErrorState';
import { EventHandlerBoard } from './game/puzzles/event-handler/EventHandlerBoard';
import { EventLog } from './game/puzzles/event-handler/EventLog';
import { FilterGroup } from '../molecules/FilterGroup';
import { Flex } from '../molecules/Flex';
import { FlipCard } from '../molecules/FlipCard';
import { FlipContainer } from '../atoms/FlipContainer';
import { FloatingActionButton } from '../molecules/FloatingActionButton';
import { Form } from './Form';
import { FormField } from '../molecules/FormField';
import { FormSectionHeader } from '../molecules/FormSectionHeader';
import { GameAudioProvider } from './game/GameAudioProvider';
import { GameAudioToggle } from './game/GameAudioToggle';
import { GameCanvas2D } from '../molecules/game/GameCanvas2D';
import { GameHud } from './game/GameHud';
import { GameMenu } from './game/GameMenu';
import { GameOverScreen } from './game/GameOverScreen';
import { GameShell } from '../templates/GameShell';
import { GameTemplate } from '../templates/GameTemplate';
import { GenericAppTemplate } from '../templates/GenericAppTemplate';
import { GraphCanvas } from './GraphCanvas';
import { GraphView } from '../molecules/GraphView';
import { Header } from './Header';
import { HealthBar } from '../atoms/game/HealthBar';
import { HealthPanel } from '../molecules/game/HealthPanel';
import { InfiniteScrollSentinel } from '../atoms/InfiniteScrollSentinel';
import { InputGroup } from '../molecules/InputGroup';
import { InventoryGrid } from '../molecules/game/InventoryGrid';
import { InventoryPanel } from './game/InventoryPanel';
import { IsometricCanvas } from '../molecules/game/IsometricCanvas';
import { ItemSlot } from '../atoms/game/ItemSlot';
import { JazariStateMachine } from './JazariStateMachine';
import { LawReferenceTooltip } from '../atoms/LawReferenceTooltip';
import { Lightbox } from '../molecules/Lightbox';
import { LineChart } from '../molecules/LineChart';
import { List } from './List';
import { LoadingState } from '../molecules/LoadingState';
import { MarkdownContent } from '../molecules/markdown/MarkdownContent';
import { MasterDetail } from './layout/MasterDetail';
import { MediaGallery } from './MediaGallery';
import { Meter } from '../molecules/Meter';
import { MiniMap } from '../atoms/game/MiniMap';
import { Modal } from '../molecules/Modal';
import { ModalSlot } from './ModalSlot';
import { Navigation } from './Navigation';
import { NegotiatorBoard } from './game/puzzles/negotiator/NegotiatorBoard';
import { NumberStepper } from '../molecules/NumberStepper';
import { ObjectRulePanel } from './game/puzzles/event-handler/ObjectRulePanel';
import { OrbitalVisualization } from './OrbitalVisualization';
import { Overlay } from '../atoms/Overlay';
import { PageHeader } from './PageHeader';
import { Pagination } from '../molecules/Pagination';
import { PlatformerCanvas } from '../molecules/game/PlatformerCanvas';
import { PowerupSlots } from '../molecules/game/PowerupSlots';
import { ProgressDots } from '../molecules/ProgressDots';
import { PullToRefresh } from '../molecules/PullToRefresh';
import { QuestTracker } from '../molecules/game/QuestTracker';
import { QuizBlock } from '../molecules/QuizBlock';
import { RangeSlider } from '../atoms/RangeSlider';
import { RelationSelect } from '../molecules/RelationSelect';
import { RepeatableFormSection } from '../molecules/RepeatableFormSection';
import { ResourceBar } from '../molecules/game/ResourceBar';
import { ResourceCounter } from '../atoms/game/ResourceCounter';
import { RuleEditor } from './game/puzzles/event-handler/RuleEditor';
import { RuntimeDebugger } from './debug/RuntimeDebugger';
import { ScaledDiagram } from '../molecules/ScaledDiagram';
import { ScoreBoard } from '../molecules/game/ScoreBoard';
import { ScoreDisplay } from '../atoms/game/ScoreDisplay';
import { SearchInput } from '../molecules/SearchInput';
import { Section } from './Section';
import { SequenceBar } from './game/puzzles/sequencer/SequenceBar';
import { SequencerBoard } from './game/puzzles/sequencer/SequencerBoard';
import { SidePanel } from '../molecules/SidePanel';
import { Sidebar } from './Sidebar';
import { SignaturePad } from './SignaturePad';
import { SimulationCanvas } from './game/physics-sim/SimulationCanvas';
import { SimulationControls } from './game/physics-sim/SimulationControls';
import { SimulationGraph } from './game/physics-sim/SimulationGraph';
import { SimulatorBoard } from './game/puzzles/simulator/SimulatorBoard';
import { Skeleton } from '../molecules/Skeleton';
import { SortableList } from '../molecules/SortableList';
import { Split } from './Split';
import { SplitPane } from './layout/SplitPane';
import { Sprite } from '../atoms/game/Sprite';
import { Stack } from '../atoms/Stack';
import { StarRating } from '../molecules/StarRating';
import { StatBadge } from '../molecules/game/StatBadge';
import { StatCard } from './StatCard';
import { StatDisplay } from '../molecules/StatDisplay';
import { StateArchitectBoard } from './game/puzzles/state-architect/StateArchitectBoard';
import { StateIndicator } from '../atoms/game/StateIndicator';
import { StateMachineView } from './StateMachineView';
import { StateNode } from './game/puzzles/state-architect/StateNode';
import { StatusDot } from '../atoms/StatusDot';
import { StatusEffect } from '../atoms/game/StatusEffect';
import { SwipeableRow } from '../molecules/SwipeableRow';
import { Switch } from '../atoms/Switch';
import { TabbedContainer } from './layout/TabbedContainer';
import { Table } from './Table';
import { Tabs } from '../molecules/Tabs';
import { TextHighlight } from '../atoms/TextHighlight';
import { ThemeToggle } from '../atoms/ThemeToggle';
import { TimeSlotCell } from '../atoms/TimeSlotCell';
import { Timeline } from './Timeline';
import { TimerDisplay } from '../atoms/game/TimerDisplay';
import { Toast } from '../molecules/Toast';
import { ToastSlot } from './ToastSlot';
import { TraitSlot } from './game/TraitSlot';
import { TraitStateViewer } from './game/TraitStateViewer';
import { TransitionArrow } from './game/puzzles/state-architect/TransitionArrow';
import { TrendIndicator } from '../atoms/TrendIndicator';
import { TurnIndicator } from '../atoms/game/TurnIndicator';
import { TurnPanel } from '../molecules/game/TurnPanel';
import { TypewriterText } from '../atoms/TypewriterText';
import { Typography } from '../atoms/Typography';
import { UISlotRenderer } from './UISlotRenderer';
import { UncontrolledBattleBoard } from './game/UncontrolledBattleBoard';
import { UnitCommandBar } from '../molecules/game/UnitCommandBar';
import { UploadDropZone } from '../molecules/UploadDropZone';
import { VariablePanel } from './game/puzzles/state-architect/VariablePanel';
import { ViolationAlert } from '../molecules/ViolationAlert';
import { WaypointMarker } from '../atoms/game/WaypointMarker';
import { WizardContainer } from './WizardContainer';
import { WizardNavigation } from '../molecules/WizardNavigation';
import { WizardProgress } from '../molecules/WizardProgress';
import { WorldMapBoard } from './game/WorldMapBoard';
import { WorldMapTemplate } from '../templates/WorldMapTemplate';
import { XPBar } from '../atoms/game/XPBar';

// ---------------------------------------------------------------------------
// Three.js components — lazy-loaded to avoid pulling @react-three/fiber into
// the main bundle. Each wrapper includes its own Suspense boundary so callers
// don't need to wrap them.
// ---------------------------------------------------------------------------
type AnyComponent = React.ComponentType<Record<string, unknown>>;
type ThreeBarrel = Record<string, AnyComponent>;

function lazyThree(
  name: string,
  loader: () => Promise<ThreeBarrel>,
): AnyComponent {
  const Lazy = React.lazy(() => loader().then(m => ({ default: m[name] })));
  function ThreeWrapper(props: Record<string, unknown>) {
    return React.createElement(
      React.Suspense,
      { fallback: null },
      React.createElement(Lazy, props),
    );
  }
  ThreeWrapper.displayName = `Lazy(${name})`;
  return ThreeWrapper;
}

const Camera3D = lazyThree('Camera3D', () => import('@almadar/ui/components/organisms/game/three'));
const Canvas3DErrorBoundary = lazyThree('Canvas3DErrorBoundary', () => import('@almadar/ui/components/organisms/game/three'));
const Canvas3DLoadingState = lazyThree('Canvas3DLoadingState', () => import('@almadar/ui/components/organisms/game/three'));
const FeatureRenderer = lazyThree('FeatureRenderer', () => import('@almadar/ui/components/organisms/game/three'));
const FeatureRenderer3D = lazyThree('FeatureRenderer3D', () => import('@almadar/ui/components/organisms/game/three'));
const GameCanvas3D = lazyThree('GameCanvas3D', () => import('@almadar/ui/components/organisms/game/three'));
const GameCanvas3DBattleTemplate = lazyThree('GameCanvas3DBattleTemplate', () => import('@almadar/ui/components/organisms/game/three'));
const GameCanvas3DCastleTemplate = lazyThree('GameCanvas3DCastleTemplate', () => import('@almadar/ui/components/organisms/game/three'));
const GameCanvas3DWorldMapTemplate = lazyThree('GameCanvas3DWorldMapTemplate', () => import('@almadar/ui/components/organisms/game/three'));
const Lighting3D = lazyThree('Lighting3D', () => import('@almadar/ui/components/organisms/game/three'));
const ModelLoader = lazyThree('ModelLoader', () => import('@almadar/ui/components/organisms/game/three'));
const PhysicsObject3D = lazyThree('PhysicsObject3D', () => import('@almadar/ui/components/organisms/game/three'));
const Scene3D = lazyThree('Scene3D', () => import('@almadar/ui/components/organisms/game/three'));
const TileRenderer = lazyThree('TileRenderer', () => import('@almadar/ui/components/organisms/game/three'));
const UnitRenderer = lazyThree('UnitRenderer', () => import('@almadar/ui/components/organisms/game/three'));

/**
 * Maps component names to actual React components.
 * Generated from @almadar/patterns component-mapping.json.
 *
 * Pattern wrappers (ButtonPattern, VStackPattern, etc.) adapt the raw component
 * API to the render-ui config format. Direct components are used when no wrapper exists.
 */
export const COMPONENT_REGISTRY: Record<string, React.ComponentType<any>> = {
  'Accordion': AccordionPattern,
  'AccordionPattern': AccordionPattern,
  'ActionButton': ActionButton,
  'ActionButtons': ActionButtons,
  'ActionPalette': ActionPalette,
  'ActionTile': ActionTile,
  'Alert': AlertPattern,
  'AlertPattern': AlertPattern,
  'AnimatedCounter': AnimatedCounter,
  'AuthLayout': AuthLayout,
  'Avatar': AvatarPattern,
  'AvatarPattern': AvatarPattern,
  'Badge': BadgePattern,
  'BadgePattern': BadgePattern,
  'BattleBoard': BattleBoard,
  'BattleTemplate': BattleTemplate,
  'BookChapterView': BookChapterView,
  'BookCoverPage': BookCoverPage,
  'BookNavBar': BookNavBar,
  'BookTableOfContents': BookTableOfContents,
  'BookViewer': BookViewer,
  'Box': BoxPattern,
  'BoxPattern': BoxPattern,
  'Breadcrumb': Breadcrumb,
  'BuilderBoard': BuilderBoard,
  'Button': ButtonPattern,
  'ButtonGroup': ButtonGroup,
  'ButtonPattern': ButtonPattern,
  'CalendarGrid': CalendarGrid,
  'Camera3D': Camera3D,
  'Canvas3DErrorBoundary': Canvas3DErrorBoundary,
  'Canvas3DLoadingState': Canvas3DLoadingState,
  'CanvasEffect': CanvasEffect,
  'Card': CardPattern,
  'CardGrid': CardGrid,
  'CardPattern': CardPattern,
  'Carousel': Carousel,
  'CastleBoard': CastleBoard,
  'CastleTemplate': CastleTemplate,
  'Center': CenterPattern,
  'CenterPattern': CenterPattern,
  'Chart': Chart,
  'ChartLegend': ChartLegend,
  'Checkbox': CheckboxPattern,
  'CheckboxPattern': CheckboxPattern,
  'ChoiceButton': ChoiceButton,
  'ClassifierBoard': ClassifierBoard,
  'CodeBlock': CodeBlock,
  'CodeView': CodeView,
  'CodeViewer': CodeViewer,
  'CombatLog': CombatLog,
  'ComboCounter': ComboCounter,
  'ConditionalWrapper': ConditionalWrapper,
  'ConfettiEffect': ConfettiEffect,
  'ConfirmDialog': ConfirmDialog,
  'Container': ContainerPattern,
  'ContainerPattern': ContainerPattern,
  'ContentRenderer': ContentRenderer,
  'ControlButton': ControlButton,
  'CounterTemplate': CounterTemplate,
  'CraftingRecipe': CraftingRecipe,
  'CustomPattern': CustomPattern,
  'DPad': DPad,
  'DamageNumber': DamageNumber,
  'DashboardGrid': DashboardGrid,
  'DashboardLayout': DashboardLayout,
  'DataGrid': DataGrid,
  'DataList': DataList,
  'DataTable': DataTable,
  'DateRangeSelector': DateRangeSelector,
  'DayCell': DayCell,
  'DebuggerBoard': DebuggerBoard,
  'DetailPanel': DetailPanel,
  'DialogueBox': DialogueBox,
  'DialogueBubble': DialogueBubble,
  'Divider': DividerPattern,
  'DividerPattern': DividerPattern,
  'DocumentViewer': DocumentViewer,
  'Drawer': Drawer,
  'DrawerSlot': DrawerSlot,
  'EmptyState': EmptyState,
  'EnemyPlate': EnemyPlate,
  'ErrorBoundary': ErrorBoundary,
  'ErrorState': ErrorState,
  'EventHandlerBoard': EventHandlerBoard,
  'EventLog': EventLog,
  'FeatureRenderer': FeatureRenderer,
  'FeatureRenderer3D': FeatureRenderer3D,
  'FilterGroup': FilterGroup,
  'Flex': Flex,
  'FlipCard': FlipCard,
  'FlipContainer': FlipContainer,
  'FloatingActionButton': FloatingActionButton,
  'Form': Form,
  'FormField': FormField,
  'FormSectionHeader': FormSectionHeader,
  'GameAudioProvider': GameAudioProvider,
  'GameAudioToggle': GameAudioToggle,
  'GameCanvas2D': GameCanvas2D,
  'GameCanvas3D': GameCanvas3D,
  'GameCanvas3DBattleTemplate': GameCanvas3DBattleTemplate,
  'GameCanvas3DCastleTemplate': GameCanvas3DCastleTemplate,
  'GameCanvas3DWorldMapTemplate': GameCanvas3DWorldMapTemplate,
  'GameHud': GameHud,
  'GameMenu': GameMenu,
  'GameOverScreen': GameOverScreen,
  'GameShell': GameShell,
  'GameTemplate': GameTemplate,
  'GenericAppTemplate': GenericAppTemplate,
  'GraphCanvas': GraphCanvas,
  'GraphView': GraphView,
  'Grid': GridPattern,
  'GridPattern': GridPattern,
  'HStack': HStackPattern,
  'HStackPattern': HStackPattern,
  'Header': Header,
  'HealthBar': HealthBar,
  'HealthPanel': HealthPanel,
  'Icon': IconPattern,
  'IconPattern': IconPattern,
  'InfiniteScrollSentinel': InfiniteScrollSentinel,
  'Input': InputPattern,
  'InputGroup': InputGroup,
  'InputPattern': InputPattern,
  'InventoryGrid': InventoryGrid,
  'InventoryPanel': InventoryPanel,
  'IsometricCanvas': IsometricCanvas,
  'ItemSlot': ItemSlot,
  'JazariStateMachine': JazariStateMachine,
  'Label': LabelPattern,
  'LabelPattern': LabelPattern,
  'LawReferenceTooltip': LawReferenceTooltip,
  'Lightbox': Lightbox,
  'Lighting3D': Lighting3D,
  'LineChart': LineChart,
  'List': List,
  'LoadingState': LoadingState,
  'MapView': MapViewPattern,
  'MapViewPattern': MapViewPattern,
  'MarkdownContent': MarkdownContent,
  'MasterDetail': MasterDetail,
  'MediaGallery': MediaGallery,
  'Menu': MenuPattern,
  'MenuPattern': MenuPattern,
  'Meter': Meter,
  'MiniMap': MiniMap,
  'Modal': Modal,
  'ModalSlot': ModalSlot,
  'ModelLoader': ModelLoader,
  'Navigation': Navigation,
  'NegotiatorBoard': NegotiatorBoard,
  'NumberStepper': NumberStepper,
  'ObjectRulePanel': ObjectRulePanel,
  'OrbitalVisualization': OrbitalVisualization,
  'Overlay': Overlay,
  'PageHeader': PageHeader,
  'Pagination': Pagination,
  'PhysicsObject3D': PhysicsObject3D,
  'PlatformerCanvas': PlatformerCanvas,
  'Popover': PopoverPattern,
  'PopoverPattern': PopoverPattern,
  'PowerupSlots': PowerupSlots,
  'ProgressBar': ProgressBarPattern,
  'ProgressBarPattern': ProgressBarPattern,
  'ProgressDots': ProgressDots,
  'PullToRefresh': PullToRefresh,
  'QuestTracker': QuestTracker,
  'QuizBlock': QuizBlock,
  'Radio': RadioPattern,
  'RadioPattern': RadioPattern,
  'RangeSlider': RangeSlider,
  'RelationSelect': RelationSelect,
  'RepeatableFormSection': RepeatableFormSection,
  'ResourceBar': ResourceBar,
  'ResourceCounter': ResourceCounter,
  'RuleEditor': RuleEditor,
  'RuntimeDebugger': RuntimeDebugger,
  'ScaledDiagram': ScaledDiagram,
  'Scene3D': Scene3D,
  'ScoreBoard': ScoreBoard,
  'ScoreDisplay': ScoreDisplay,
  'SearchInput': SearchInput,
  'Section': Section,
  'Select': SelectPattern,
  'SelectPattern': SelectPattern,
  'SequenceBar': SequenceBar,
  'SequencerBoard': SequencerBoard,
  'SidePanel': SidePanel,
  'Sidebar': Sidebar,
  'SignaturePad': SignaturePad,
  'SimpleGrid': SimpleGridPattern,
  'SimpleGridPattern': SimpleGridPattern,
  'SimulationCanvas': SimulationCanvas,
  'SimulationControls': SimulationControls,
  'SimulationGraph': SimulationGraph,
  'SimulatorBoard': SimulatorBoard,
  'Skeleton': Skeleton,
  'SortableList': SortableList,
  'Spacer': SpacerPattern,
  'SpacerPattern': SpacerPattern,
  'Spinner': SpinnerPattern,
  'SpinnerPattern': SpinnerPattern,
  'Split': Split,
  'SplitPane': SplitPane,
  'Sprite': Sprite,
  'Stack': Stack,
  'StarRating': StarRating,
  'StatBadge': StatBadge,
  'StatCard': StatCard,
  'StatDisplay': StatDisplay,
  'StateArchitectBoard': StateArchitectBoard,
  'StateIndicator': StateIndicator,
  'StateMachineView': StateMachineView,
  'StateNode': StateNode,
  'StatusDot': StatusDot,
  'StatusEffect': StatusEffect,
  'SwipeableRow': SwipeableRow,
  'Switch': Switch,
  'TabbedContainer': TabbedContainer,
  'Table': Table,
  'Tabs': Tabs,
  'TextHighlight': TextHighlight,
  'Textarea': TextareaPattern,
  'TextareaPattern': TextareaPattern,
  'ThemeToggle': ThemeToggle,
  'TileRenderer': TileRenderer,
  'TimeSlotCell': TimeSlotCell,
  'Timeline': Timeline,
  'TimerDisplay': TimerDisplay,
  'Toast': Toast,
  'ToastSlot': ToastSlot,
  'Tooltip': TooltipPattern,
  'TooltipPattern': TooltipPattern,
  'TraitSlot': TraitSlot,
  'TraitStateViewer': TraitStateViewer,
  'TransitionArrow': TransitionArrow,
  'TrendIndicator': TrendIndicator,
  'TurnIndicator': TurnIndicator,
  'TurnPanel': TurnPanel,
  'TypewriterText': TypewriterText,
  'Typography': Typography,
  'UISlotRenderer': UISlotRenderer,
  'UncontrolledBattleBoard': UncontrolledBattleBoard,
  'UnitCommandBar': UnitCommandBar,
  'UnitRenderer': UnitRenderer,
  'UploadDropZone': UploadDropZone,
  'VStack': VStackPattern,
  'VStackPattern': VStackPattern,
  'VariablePanel': VariablePanel,
  'ViolationAlert': ViolationAlert,
  'WaypointMarker': WaypointMarker,
  'WizardContainer': WizardContainer,
  'WizardNavigation': WizardNavigation,
  'WizardProgress': WizardProgress,
  'WorldMapBoard': WorldMapBoard,
  'WorldMapTemplate': WorldMapTemplate,
  'XPBar': XPBar,

  // Semantic aliases
  'Text': TextPattern,
};
