'use client';
/**
 * Card Component
 *
 * A generic card container for displaying content with optional title,
 * subtitle, and action buttons.
 *
 * @generated by Orbital Compiler
 */

import React, { useCallback } from "react";
import type { AssetUrl, EventEmit, EventKey, EventPayload } from "@almadar/core";
import type { IconInput } from "../atoms/index";
import { useEventBus } from "../../../hooks/useEventBus";
import { useTranslate } from "../../../hooks/useTranslate";
import { useLongPress } from "../../../hooks/useLongPress";
import { Card as AtomCard } from "../atoms/Card";
import { Box } from "../atoms/Box";
import { Button } from "../atoms/Button";
import { Image } from "../atoms/Image";
import { Typography } from "../atoms/Typography";
import { HStack } from "../atoms/Stack";
import { cn } from "../../../lib/cn";

export interface CardAction {
  label: string;
  onClick?: () => void;
  /** Event name to emit when clicked (for trait state machine integration) */
  event?: string;
  variant?: "default" | "primary" | "danger";
  icon?: IconInput;
  disabled?: boolean;
}

export interface CardProps {
  /** Card title */
  title?: string;
  /** Card subtitle or description */
  subtitle?: string;
  /** Image URL to display at top of card */
  image?: AssetUrl;
  /** Action buttons to display in card footer */
  actions?: CardAction[];
  /** Card content */
  children?: React.ReactNode;
  /** Click handler for the entire card */
  onClick?: () => void;
  /** Additional CSS classes */
  className?: string;
  /** Declarative event name — emits UI:{action} via eventBus on card click */
  action?: EventKey;
  /** Whether the card is selected (highlighted state) */
  isSelected?: boolean;
  /** Card name (alias for title) */
  name?: string;
  /** Level indicator */
  level?: number;
  /** Maximum level */
  maxLevel?: number;
  /** Event emitted on long press: UI:{longPressEvent} (payload: longPressPayload spread — variable) */
  longPressEvent?: EventEmit<EventPayload>;
  /** Additional payload for long-press events
   *  @payloadFor longPressEvent
   */
  longPressPayload?: EventPayload;
}

/**
 * Card component for displaying content in a contained box
 */
export function Card({
  title,
  subtitle,
  image,
  actions,
  children,
  onClick,
  className = "",
  action,
  longPressEvent,
  longPressPayload,
}: CardProps) {
  const eventBus = useEventBus();
  const { t } = useTranslate();
  const isClickable = !!onClick || !!action;

  const handleLongPress = useCallback(() => {
    if (longPressEvent) {
      eventBus.emit(`UI:${longPressEvent}`, longPressPayload ?? {});
    }
  }, [longPressEvent, longPressPayload, eventBus]);

  const longPress = useLongPress(handleLongPress);

  const handleClick = () => {
    if (action) eventBus.emit(`UI:${action}`, {});
    onClick?.();
  };

  return (
    <AtomCard
      padding="none"
      className={cn(isClickable && "hover:shadow-elevation-dialog transition-shadow", className)}
      onClick={isClickable ? handleClick : undefined}
      {...(longPressEvent ? {
        onPointerDown: longPress.onPointerDown,
        onPointerMove: longPress.onPointerMove,
        onPointerUp: longPress.onPointerUp,
        onPointerCancel: longPress.onPointerCancel,
      } : {})}
    >
      {image && (
        <Box className="aspect-video w-full overflow-hidden rounded-t-container">
          <Image src={image} alt={title || t('card.imageAlt')} className="w-full h-full object-cover" />
        </Box>
      )}

      <Box className="p-4">
        {(title || subtitle) && (
          <Box className="mb-3">
            {title && (
              <Typography variant="h5" as="h3" className="text-card-foreground">
                {title}
              </Typography>
            )}
            {subtitle && (
              <Typography variant="small" color="muted" className="mt-1">
                {subtitle}
              </Typography>
            )}
          </Box>
        )}

        {children && <Box className="text-card-foreground">{children}</Box>}

        {actions && actions.length > 0 && (
          <HStack gap="sm" wrap className="mt-4 pt-4 border-t border-border">
            {actions.map((cardAction, index) => (
              <Button
                key={index}
                size="sm"
                variant={cardAction.variant === "primary" ? "primary" : cardAction.variant === "danger" ? "danger" : "secondary"}
                leftIcon={cardAction.icon}
                disabled={cardAction.disabled}
                onClick={(e: React.MouseEvent) => {
                  e.stopPropagation();
                  if (cardAction.event) eventBus.emit(`UI:${cardAction.event}`, { label: cardAction.label });
                  cardAction.onClick?.();
                }}
              >
                {cardAction.label}
              </Button>
            ))}
          </HStack>
        )}
      </Box>
    </AtomCard>
  );
}

Card.displayName = 'Card';

export default Card;
