'use client';
/**
 * Card Component
 *
 * A generic card container for displaying content with optional title,
 * subtitle, and action buttons.
 *
 * @generated by Orbital Compiler
 */

import React, { useCallback } from "react";
import { useEventBus } from "../../hooks/useEventBus";
import { useTranslate } from "../../hooks/useTranslate";
import { useLongPress } from "../../hooks/useLongPress";

export interface CardAction {
  label: string;
  onClick?: () => void;
  /** Event name to emit when clicked (for trait state machine integration) */
  event?: string;
  variant?: "default" | "primary" | "danger";
  icon?: string;
  disabled?: boolean;
}

export interface CardProps {
  /** Card title */
  title?: string;
  /** Card subtitle or description */
  subtitle?: string;
  /** Image URL to display at top of card */
  image?: string;
  /** Action buttons to display in card footer */
  actions?: CardAction[];
  /** Card content */
  children?: React.ReactNode;
  /** Click handler for the entire card */
  onClick?: () => void;
  /** Additional CSS classes */
  className?: string;
  /** Declarative event name — emits UI:{action} via eventBus on card click */
  action?: string;
  /** Whether the card is selected (highlighted state) */
  isSelected?: boolean;
  /** Card name (alias for title) */
  name?: string;
  /** Level indicator */
  level?: number;
  /** Maximum level */
  maxLevel?: number;
  /** Event emitted on long press: UI:{longPressEvent} */
  longPressEvent?: string;
  /** Additional payload for long-press events */
  longPressPayload?: Record<string, unknown>;
}

/**
 * Card component for displaying content in a contained box
 */
export function Card({
  title,
  subtitle,
  image,
  actions,
  children,
  onClick,
  className = "",
  action,
  longPressEvent,
  longPressPayload,
}: CardProps) {
  const eventBus = useEventBus();
  const { t } = useTranslate();
  const isClickable = !!onClick || !!action;

  const handleLongPress = useCallback(() => {
    if (longPressEvent) {
      eventBus.emit(`UI:${longPressEvent}`, longPressPayload ?? {});
    }
  }, [longPressEvent, longPressPayload, eventBus]);

  const longPress = useLongPress(handleLongPress);

  const handleClick = () => {
    if (action) eventBus.emit(`UI:${action}`, {});
    onClick?.();
  };

  return (
    <div
      className={`
        bg-card
        border border-border
        rounded-md shadow-sm
        ${isClickable ? "cursor-pointer hover:shadow-lg transition-shadow" : ""}
        ${className}
      `}
      onClick={isClickable ? handleClick : undefined}
      role={isClickable ? "button" : undefined}
      tabIndex={isClickable ? 0 : undefined}
      onKeyDown={
        isClickable ? (e) => e.key === "Enter" && handleClick() : undefined
      }
      {...(longPressEvent ? {
        onPointerDown: longPress.onPointerDown,
        onPointerMove: longPress.onPointerMove,
        onPointerUp: longPress.onPointerUp,
        onPointerCancel: longPress.onPointerCancel,
      } : {})}
    >
      {/* Image */}
      {image && (
        <div className="aspect-video w-full overflow-hidden rounded-t-lg">
          <img
            src={image}
            alt={title || t('card.imageAlt')}
            className="w-full h-full object-cover"
          />
        </div>
      )}

      {/* Content */}
      <div className="p-4">
        {/* Header */}
        {(title || subtitle) && (
          <div className="mb-3">
            {title && (
              <h3 className="text-lg font-semibold text-card-foreground">
                {title}
              </h3>
            )}
            {subtitle && (
              <p className="text-sm text-muted-foreground mt-1">
                {subtitle}
              </p>
            )}
          </div>
        )}

        {/* Children */}
        {children && (
          <div className="text-card-foreground">{children}</div>
        )}

        {/* Actions */}
        {actions && actions.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-border">
            {actions.map((action, index) => (
              <button
                key={index}
                onClick={(e) => {
                  e.stopPropagation();
                  if (action.event) eventBus.emit(`UI:${action.event}`, { label: action.label });
                  action.onClick?.();
                }}
                disabled={action.disabled}
                className={`
                  px-3 py-1.5 text-sm font-medium rounded-sm
                  transition-colors
                  ${
                    action.variant === "primary"
                      ? "bg-primary text-primary-foreground hover:bg-primary-hover disabled:opacity-50"
                      : action.variant === "danger"
                        ? "bg-error text-error-foreground hover:opacity-90 disabled:opacity-50"
                        : "bg-muted text-foreground hover:bg-[var(--color-surface-hover)]"
                  }
                  disabled:cursor-not-allowed
                `}
              >
                {action.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

Card.displayName = 'Card';

export default Card;
