// AUTO-GENERATED by tools/almadar-pattern-sync/generate-component-registry.ts
// Do not edit manually. Re-run the generator after adding components.
//
// Generated: 2026-07-05T19:20:55.897Z
// Patterns: 287
// Components: 292
// Lazy (Three.js): 1

import React from 'react';

import { AboutPageTemplate } from '../../marketing/templates/AboutPageTemplate';
import { Accordion } from '../molecules/Accordion';
import { ActionButton } from '../../game/atoms/ActionButton';
import { ActionPalette } from '../../game/molecules/ActionPalette';
import { ActionTile } from '../../game/molecules/ActionTile';
import { ActivationBlock } from '../molecules/ActivationBlock';
import { AlertPattern, ButtonPattern, FloatButtonPattern, IconButtonPattern, ImagePattern, LabelPattern, LinkPattern, TextPattern } from './ComponentPatterns';
import { AlgorithmCanvas } from '../../learning/molecules/AlgorithmCanvas';
import { AnimatedCounter } from '../../marketing/atoms/AnimatedCounter';
import { AnimatedGraphic } from '../../marketing/atoms/AnimatedGraphic';
import { AnimatedReveal } from '../../marketing/atoms/AnimatedReveal';
import { ArticleSection } from '../../marketing/molecules/ArticleSection';
import { Aside } from '../atoms/Aside';
import { AtlasImage, AtlasPanel } from '../atoms/AtlasImage';
import { AuthLayout } from '../../marketing/templates/AuthLayout';
import { Avatar } from '../atoms/Avatar';
import { Badge } from '../atoms/Badge';
import { BehaviorView } from '../../avl/molecules/BehaviorView';
import { BiologyCanvas } from '../../learning/molecules/BiologyCanvas';
import { BloomQuizBlock } from '../molecules/BloomQuizBlock';
import { BookChapterView } from '../../marketing/organisms/book/BookChapterView';
import { BookCoverPage } from '../../marketing/organisms/book/BookCoverPage';
import { BookNavBar } from '../../marketing/organisms/book/BookNavBar';
import { BookTableOfContents } from '../../marketing/organisms/book/BookTableOfContents';
import { BookViewer } from '../../marketing/organisms/book/BookViewer';
import { BoxPattern, DividerPattern, SpacerPattern } from './LayoutPatterns';
import { BranchingLogicBuilder } from '../molecules/BranchingLogicBuilder';
import { Breadcrumb } from '../molecules/Breadcrumb';
import { CTABanner } from '../../marketing/molecules/CTABanner';
import { CalendarGrid } from '../molecules/CalendarGrid';
import { Canvas } from '../../game/molecules/Canvas';
import { Canvas2D } from '../../game/molecules/Canvas2D';
import { Card } from '../atoms/Card';
import { CardGrid } from './CardGrid';
import { Carousel } from '../molecules/Carousel';
import { CaseStudyCard } from '../../marketing/molecules/CaseStudyCard';
import { CaseStudyOrganism } from '../../marketing/organisms/CaseStudyOrganism';
import { Center } from '../atoms/Center';
import { Chart } from '../molecules/Chart';
import { ChartLegend } from '../molecules/ChartLegend';
import { ChatBar } from './ChatBar';
import { Checkbox } from '../atoms/Checkbox';
import { ChemistryCanvas } from '../../learning/molecules/ChemistryCanvas';
import { ChoiceButton } from '../../game/atoms/ChoiceButton';
import { CodeBlock } from '../molecules/markdown/CodeBlock';
import { CodeRunnerPanel } from './CodeRunnerPanel';
import { ComboCounter } from '../../game/atoms/ComboCounter';
import { CommunityLinks } from '../../marketing/molecules/CommunityLinks';
import { ConditionalWrapper } from '../atoms/ConditionalWrapper';
import { ConfettiEffect } from '../atoms/ConfettiEffect';
import { ConfirmDialog } from '../molecules/ConfirmDialog';
import { ConnectionBlock } from '../molecules/ConnectionBlock';
import { Container } from '../molecules/Container';
import { ContentRenderer } from '../molecules/ContentRenderer';
import { ContentSection } from '../../marketing/atoms/ContentSection';
import { ControlButton } from '../../game/atoms/ControlButton';
import { ControlGrid } from '../../game/molecules/ControlGrid';
import { CounterTemplate } from '../templates/CounterTemplate';
import { CustomPattern } from './CustomPattern';
import { DamageNumber } from '../../game/atoms/DamageNumber';
import { DashboardGrid } from './layout/DashboardGrid';
import { DashboardLayout } from '../templates/DashboardLayout';
import { DataGrid } from '../molecules/DataGrid';
import { DataList } from '../molecules/DataList';
import { DataTable } from './DataTable';
import { DateRangePicker } from '../molecules/DateRangePicker';
import { DateRangeSelector } from '../molecules/DateRangeSelector';
import { DayCell } from '../atoms/DayCell';
import { DetailPanel } from './DetailPanel';
import { Dialog } from '../atoms/Dialog';
import { DialogueBubble } from '../../game/atoms/DialogueBubble';
import { DocBreadcrumb } from '../molecules/DocBreadcrumb';
import { DocPagination } from '../molecules/DocPagination';
import { DocSearch } from '../molecules/DocSearch';
import { DocSidebar } from '../molecules/DocSidebar';
import { DocTOC } from '../molecules/DocTOC';
import { DocumentViewer } from '../molecules/DocumentViewer';
import { DrawShape } from '../../game/atoms/DrawShape';
import { DrawShapeLayer } from '../../game/molecules/DrawShapeLayer';
import { DrawSprite } from '../../game/atoms/DrawSprite';
import { DrawSpriteLayer } from '../../game/molecules/DrawSpriteLayer';
import { DrawText } from '../../game/atoms/DrawText';
import { DrawTextLayer } from '../../game/molecules/DrawTextLayer';
import { Drawer } from '../molecules/Drawer';
import { DrawerSlot } from './DrawerSlot';
import { EdgeDecoration } from '../molecules/EdgeDecoration';
import { EmptyState } from '../molecules/EmptyState';
import { ErrorBoundary } from '../molecules/ErrorBoundary';
import { ErrorState } from '../molecules/ErrorState';
import { EventLog } from '../../game/molecules/EventLog';
import { FeatureCard } from '../../marketing/molecules/FeatureCard';
import { FeatureDetailPageTemplate } from '../../marketing/templates/FeatureDetailPageTemplate';
import { FeatureGrid } from '../molecules/FeatureGrid';
import { FeatureGridOrganism } from '../../marketing/organisms/FeatureGridOrganism';
import { FileTree } from '../molecules/FileTree';
import { FilterGroup } from '../molecules/FilterGroup';
import { FilterPill } from '../atoms/FilterPill';
import { Flex } from '../molecules/Flex';
import { FlipCard } from '../molecules/FlipCard';
import { FlipContainer } from '../atoms/FlipContainer';
import { FloatingActionButton } from '../molecules/FloatingActionButton';
import { Form } from './Form';
import { FormActions, FormLayout } from '../molecules/FormSection';
import { FormField } from '../molecules/FormField';
import { FormSectionHeader } from '../molecules/FormSectionHeader';
import { GameAudioToggle } from '../../game/atoms/GameAudioToggle';
import { GameCard } from '../../game/atoms/GameCard';
import { GameHud } from '../../game/molecules/GameHud';
import { GameIcon } from '../../game/atoms/GameIcon';
import { GameMenu } from '../../game/molecules/GameMenu';
import { GameShell } from '../../game/templates/GameShell';
import { GameTemplate } from '../../game/templates/GameTemplate';
import { GenericAppTemplate } from '../templates/GenericAppTemplate';
import { GeometricPattern } from '../../marketing/molecules/GeometricPattern';
import { GradientDivider } from '../molecules/GradientDivider';
import { GraphCanvas } from '../molecules/GraphCanvas';
import { GraphView } from '../molecules/GraphView';
import { Grid } from '../molecules/Grid';
import { HStack, Stack, VStack } from '../atoms/Stack';
import { Header } from '../molecules/Header';
import { HealthBar } from '../../game/atoms/HealthBar';
import { HeroOrganism } from '../../marketing/organisms/HeroOrganism';
import { HeroSection } from '../../marketing/molecules/HeroSection';
import { Icon } from '../atoms/Icon';
import { InfiniteScrollSentinel } from '../atoms/InfiniteScrollSentinel';
import { Input } from '../atoms/Input';
import { InputGroup } from '../molecules/InputGroup';
import { InstallBox } from '../../marketing/molecules/InstallBox';
import { InventoryGrid } from '../../game/molecules/InventoryGrid';
import { ItemSlot } from '../../game/atoms/ItemSlot';
import { JazariStateMachine } from '../molecules/JazariStateMachine';
import { LandingPageTemplate } from '../../marketing/templates/LandingPageTemplate';
import { LawReferenceTooltip } from '../atoms/LawReferenceTooltip';
import { LearningCanvas } from '../../learning/atoms/LearningCanvas';
import { Lightbox } from '../molecules/Lightbox';
import { LikertScale } from '../molecules/LikertScale';
import { LineChart } from '../molecules/LineChart';
import { List } from './List';
import { LoadingState } from '../molecules/LoadingState';
import { MapView } from '../molecules/MapView';
import { MarkdownContent } from '../molecules/markdown/MarkdownContent';
import { MarketingFooter } from '../../marketing/molecules/MarketingFooter';
import { MarketingStatCard } from '../../marketing/atoms/MarketingStatCard';
import { MasterDetail } from './MasterDetail';
import { MasterDetailLayout } from './layout/MasterDetailLayout';
import { MathCanvas } from '../../learning/molecules/MathCanvas';
import { MatrixQuestion } from '../molecules/MatrixQuestion';
import { MediaGallery } from './MediaGallery';
import { Menu } from '../molecules/Menu';
import { Meter } from '../molecules/Meter';
import { MiniMap } from '../../game/atoms/MiniMap';
import { Modal } from '../molecules/Modal';
import { ModalSlot } from './ModalSlot';
import { ModuleCard } from '../../avl/molecules/ModuleCard';
import { Navigation } from '../molecules/Navigation';
import { NumberStepper } from '../molecules/NumberStepper';
import { ObjectRulePanel } from '../../game/molecules/ObjectRulePanel';
import { OptionConstraintGroup } from '../molecules/OptionConstraintGroup';
import { OrbitalVisualization } from '../molecules/OrbitalVisualization';
import { Overlay } from '../atoms/Overlay';
import { PageHeader } from '../molecules/PageHeader';
import { Pagination } from '../molecules/Pagination';
import { PatternTile } from '../../marketing/atoms/PatternTile';
import { PhysicsCanvas } from '../../learning/molecules/PhysicsCanvas';
import { Popover } from '../molecules/Popover';
import { PositionedCanvas } from '../molecules/PositionedCanvas';
import { PricingCard } from '../../marketing/molecules/PricingCard';
import { PricingGrid } from '../../marketing/molecules/PricingGrid';
import { PricingOrganism } from '../../marketing/organisms/PricingOrganism';
import { PricingPageTemplate } from '../../marketing/templates/PricingPageTemplate';
import { ProgressBar } from '../atoms/ProgressBar';
import { ProgressDots } from '../molecules/ProgressDots';
import { PullQuote } from '../../marketing/molecules/PullQuote';
import { PullToRefresh } from '../molecules/PullToRefresh';
import { QrScanner } from '../molecules/QrScanner';
import { QuizBlock } from '../molecules/QuizBlock';
import { Radio } from '../atoms/Radio';
import { RangeSlider } from '../atoms/RangeSlider';
import { ReflectionBlock } from '../molecules/ReflectionBlock';
import { RelationSelect } from '../molecules/RelationSelect';
import { RepeatableFormSection } from '../molecules/RepeatableFormSection';
import { ReplyTree } from '../molecules/ReplyTree';
import { ResourceBar } from '../../game/molecules/ResourceBar';
import { ResourceCounter } from '../../game/atoms/ResourceCounter';
import { RichBlockEditor } from '../molecules/RichBlockEditor';
import { RuntimeDebugger } from './debug/RuntimeDebugger';
import { ScaledDiagram } from '../molecules/ScaledDiagram';
import { ScoreDisplay } from '../../game/atoms/ScoreDisplay';
import { SearchInput } from '../molecules/SearchInput';
import { Section } from '../molecules/Section';
import { SectionHeader } from '../atoms/SectionHeader';
import { SegmentRenderer } from './SegmentRenderer';
import { Select } from '../atoms/Select';
import { SequenceBar } from '../../game/molecules/SequenceBar';
import { ServiceCatalog } from '../../marketing/molecules/ServiceCatalog';
import { ShowcaseCard } from '../../marketing/molecules/ShowcaseCard';
import { ShowcaseOrganism } from '../../marketing/organisms/ShowcaseOrganism';
import { SidePanel } from '../molecules/SidePanel';
import { Sidebar } from '../molecules/Sidebar';
import { SignaturePad } from '../molecules/SignaturePad';
import { SimpleGrid } from '../molecules/SimpleGrid';
import { Skeleton } from '../molecules/Skeleton';
import { SocialProof } from '../molecules/SocialProof';
import { SortableList } from '../molecules/SortableList';
import { Sparkline } from '../atoms/Sparkline';
import { Spinner } from '../atoms/Spinner';
import { Split } from '../molecules/Split';
import { SplitPane } from './layout/SplitPane';
import { SplitSection } from '../../marketing/molecules/SplitSection';
import { Sprite } from '../../game/atoms/Sprite';
import { StarRating } from '../molecules/StarRating';
import { StatBadge } from '../../game/molecules/StatBadge';
import { StatCard } from './StatCard';
import { StatDisplay } from '../molecules/StatDisplay';
import { StateGraph } from '../../game/molecules/StateGraph';
import { StateIndicator } from '../../game/atoms/StateIndicator';
import { StateJsonView } from '../../game/molecules/StateJsonView';
import { StateMachineView } from './StateMachineView';
import { StatsGrid } from '../../marketing/molecules/StatsGrid';
import { StatsOrganism } from '../../marketing/organisms/StatsOrganism';
import { StatusDot } from '../atoms/StatusDot';
import { StatusEffect } from '../../game/atoms/StatusEffect';
import { StepFlow } from '../../marketing/molecules/StepFlow';
import { StepFlowOrganism } from '../../marketing/organisms/StepFlowOrganism';
import { SubagentTracePanel } from './SubagentTracePanel';
import { SvgBranch } from '../atoms/svg/SvgBranch';
import { SvgConnection } from '../atoms/svg/SvgConnection';
import { SvgFlow } from '../atoms/svg/SvgFlow';
import { SvgGrid } from '../atoms/svg/SvgGrid';
import { SvgLobe } from '../atoms/svg/SvgLobe';
import { SvgMesh } from '../atoms/svg/SvgMesh';
import { SvgMorph } from '../atoms/svg/SvgMorph';
import { SvgNode } from '../atoms/svg/SvgNode';
import { SvgPulse } from '../atoms/svg/SvgPulse';
import { SvgRing } from '../atoms/svg/SvgRing';
import { SvgShield } from '../atoms/svg/SvgShield';
import { SvgStack } from '../atoms/svg/SvgStack';
import { SwipeableRow } from '../molecules/SwipeableRow';
import { Switch } from '../atoms/Switch';
import { TabbedContainer } from './layout/TabbedContainer';
import { TableView } from '../molecules/TableView';
import { Tabs } from '../molecules/Tabs';
import { TagCloud } from '../../marketing/molecules/TagCloud';
import { TagInput } from '../molecules/TagInput';
import { TeamCard } from '../../marketing/molecules/TeamCard';
import { TeamOrganism } from '../../marketing/organisms/TeamOrganism';
import { TextHighlight } from '../atoms/TextHighlight';
import { Textarea } from '../atoms/Textarea';
import { ThemeToggle } from '../atoms/ThemeToggle';
import { TimeSlotCell } from '../atoms/TimeSlotCell';
import { Timeline } from './Timeline';
import { TimerDisplay } from '../../game/atoms/TimerDisplay';
import { Toast } from '../molecules/Toast';
import { ToastSlot } from './ToastSlot';
import { Tooltip } from '../molecules/Tooltip';
import { TraitFrame } from '../atoms/TraitFrame';
import { TraitSlot } from '../../game/molecules/TraitSlot';
import { TrendIndicator } from '../atoms/TrendIndicator';
import { TurnIndicator } from '../../game/atoms/TurnIndicator';
import { TypewriterText } from '../atoms/TypewriterText';
import { Typography } from '../atoms/Typography';
import { UISlotRenderer } from './UISlotRenderer';
import { UploadDropZone } from '../molecules/UploadDropZone';
import { VariablePanel } from '../../game/molecules/VariablePanel';
import { VersionDiff } from '../molecules/VersionDiff';
import { ViolationAlert } from '../molecules/ViolationAlert';
import { VoteStack } from '../molecules/VoteStack';
import { WaypointMarker } from '../../game/atoms/WaypointMarker';
import { WizardContainer } from '../molecules/WizardContainer';
import { WizardNavigation } from '../molecules/WizardNavigation';
import { WizardProgress } from '../molecules/WizardProgress';

// ---------------------------------------------------------------------------
// Three.js components — code-split behind the optional
// @almadar/ui/components/molecules/game/three subpath so @react-three/fiber is
// never pulled into the main bundle. three / @react-three/* are OPTIONAL peer
// dependencies: a host that does not install them (or pins a mismatched React)
// must degrade gracefully, not crash the whole render tree. Each wrapper owns
// its Suspense boundary AND an error boundary that renders a clear placeholder
// instead of letting a failed dynamic import bubble to the app root.
// ---------------------------------------------------------------------------
type AnyComponent = React.ComponentType<Record<string, unknown>>;

class ThreeBoundary extends React.Component<
  { name: string; children?: React.ReactNode },
  { failed: boolean }
> {
  state = { failed: false };
  static getDerivedStateFromError() {
    return { failed: true };
  }
  render() {
    if (this.state.failed) {
      return React.createElement(
        'div',
        {
          'data-testid': 'three-unavailable',
          style: { padding: 16, fontSize: 13, lineHeight: 1.5, opacity: 0.7 },
        },
        `3D pattern "${this.props.name}" requires three.js. Install the optional peers ` +
          'three + @react-three/fiber + @react-three/drei (matching the host React major) to render it.',
      );
    }
    return this.props.children;
  }
}

function lazyThree(
  name: string,
  loader: () => Promise<Record<string, unknown>>,
): AnyComponent {
  const Lazy = React.lazy(() =>
    loader().then(m => {
      const Resolved = m[name] as unknown as AnyComponent | undefined;
      if (!Resolved) {
        throw new Error(
          `[@almadar/ui] 3D component "${name}" was not found in the three subpath bundle.`,
        );
      }
      return { default: Resolved };
    }),
  );
  function ThreeWrapper(props: Record<string, unknown>) {
    return React.createElement(
      ThreeBoundary,
      { name },
      React.createElement(
        React.Suspense,
        { fallback: null },
        React.createElement(Lazy, props),
      ),
    );
  }
  ThreeWrapper.displayName = `Lazy(${name})`;
  return ThreeWrapper;
}

const GameCanvas3D = lazyThree('GameCanvas3D', () => import('@almadar/ui/components/molecules/game/three'));

/**
 * Maps component names to actual React components.
 * Generated from @almadar/patterns component-mapping.json.
 *
 * Pattern wrappers (ButtonPattern, VStackPattern, etc.) adapt the raw component
 * API to the render-ui config format. Direct components are used when no wrapper exists.
 */
export const COMPONENT_REGISTRY: Record<string, React.ComponentType<any>> = {
  'AboutPageTemplate': AboutPageTemplate,
  'Accordion': Accordion,
  'ActionButton': ActionButton,
  'ActionPalette': ActionPalette,
  'ActionTile': ActionTile,
  'ActivationBlock': ActivationBlock,
  'Alert': AlertPattern,
  'AlertPattern': AlertPattern,
  'AlgorithmCanvas': AlgorithmCanvas,
  'AnimatedCounter': AnimatedCounter,
  'AnimatedGraphic': AnimatedGraphic,
  'AnimatedReveal': AnimatedReveal,
  'ArticleSection': ArticleSection,
  'Aside': Aside,
  'AtlasImage': AtlasImage,
  'AtlasPanel': AtlasPanel,
  'AuthLayout': AuthLayout,
  'Avatar': Avatar,
  'Badge': Badge,
  'BehaviorView': BehaviorView,
  'BiologyCanvas': BiologyCanvas,
  'BloomQuizBlock': BloomQuizBlock,
  'BookChapterView': BookChapterView,
  'BookCoverPage': BookCoverPage,
  'BookNavBar': BookNavBar,
  'BookTableOfContents': BookTableOfContents,
  'BookViewer': BookViewer,
  'Box': BoxPattern,
  'BoxPattern': BoxPattern,
  'BranchingLogicBuilder': BranchingLogicBuilder,
  'Breadcrumb': Breadcrumb,
  'Button': ButtonPattern,
  'ButtonPattern': ButtonPattern,
  'CTABanner': CTABanner,
  'CalendarGrid': CalendarGrid,
  'Canvas': Canvas,
  'Canvas2D': Canvas2D,
  'Card': Card,
  'CardGrid': CardGrid,
  'Carousel': Carousel,
  'CaseStudyCard': CaseStudyCard,
  'CaseStudyOrganism': CaseStudyOrganism,
  'Center': Center,
  'Chart': Chart,
  'ChartLegend': ChartLegend,
  'ChatBar': ChatBar,
  'Checkbox': Checkbox,
  'ChemistryCanvas': ChemistryCanvas,
  'ChoiceButton': ChoiceButton,
  'CodeBlock': CodeBlock,
  'CodeRunnerPanel': CodeRunnerPanel,
  'ComboCounter': ComboCounter,
  'CommunityLinks': CommunityLinks,
  'ConditionalWrapper': ConditionalWrapper,
  'ConfettiEffect': ConfettiEffect,
  'ConfirmDialog': ConfirmDialog,
  'ConnectionBlock': ConnectionBlock,
  'Container': Container,
  'ContentRenderer': ContentRenderer,
  'ContentSection': ContentSection,
  'ControlButton': ControlButton,
  'ControlGrid': ControlGrid,
  'CounterTemplate': CounterTemplate,
  'DamageNumber': DamageNumber,
  'DashboardGrid': DashboardGrid,
  'DashboardLayout': DashboardLayout,
  'DataGrid': DataGrid,
  'DataList': DataList,
  'DataTable': DataTable,
  'DateRangePicker': DateRangePicker,
  'DateRangeSelector': DateRangeSelector,
  'DayCell': DayCell,
  'DetailPanel': DetailPanel,
  'Dialog': Dialog,
  'DialogueBubble': DialogueBubble,
  'Divider': DividerPattern,
  'DividerPattern': DividerPattern,
  'DocBreadcrumb': DocBreadcrumb,
  'DocPagination': DocPagination,
  'DocSearch': DocSearch,
  'DocSidebar': DocSidebar,
  'DocTOC': DocTOC,
  'DocumentViewer': DocumentViewer,
  'DrawShape': DrawShape,
  'DrawShapeLayer': DrawShapeLayer,
  'DrawSprite': DrawSprite,
  'DrawSpriteLayer': DrawSpriteLayer,
  'DrawText': DrawText,
  'DrawTextLayer': DrawTextLayer,
  'Drawer': Drawer,
  'DrawerSlot': DrawerSlot,
  'EdgeDecoration': EdgeDecoration,
  'EmptyState': EmptyState,
  'ErrorBoundary': ErrorBoundary,
  'ErrorState': ErrorState,
  'EventLog': EventLog,
  'FeatureCard': FeatureCard,
  'FeatureDetailPageTemplate': FeatureDetailPageTemplate,
  'FeatureGrid': FeatureGrid,
  'FeatureGridOrganism': FeatureGridOrganism,
  'FileTree': FileTree,
  'FilterGroup': FilterGroup,
  'FilterPill': FilterPill,
  'Flex': Flex,
  'FlipCard': FlipCard,
  'FlipContainer': FlipContainer,
  'FloatingActionButton': FloatingActionButton,
  'Form': Form,
  'FormActions': FormActions,
  'FormField': FormField,
  'FormLayout': FormLayout,
  'FormSectionHeader': FormSectionHeader,
  'GameAudioToggle': GameAudioToggle,
  'GameCanvas3D': GameCanvas3D,
  'GameCard': GameCard,
  'GameHud': GameHud,
  'GameIcon': GameIcon,
  'GameMenu': GameMenu,
  'GameShell': GameShell,
  'GameTemplate': GameTemplate,
  'GenericAppTemplate': GenericAppTemplate,
  'GeometricPattern': GeometricPattern,
  'GradientDivider': GradientDivider,
  'GraphCanvas': GraphCanvas,
  'GraphView': GraphView,
  'Grid': Grid,
  'HStack': HStack,
  'Header': Header,
  'HealthBar': HealthBar,
  'HeroOrganism': HeroOrganism,
  'HeroSection': HeroSection,
  'Icon': Icon,
  'InfiniteScrollSentinel': InfiniteScrollSentinel,
  'Input': Input,
  'InputGroup': InputGroup,
  'InstallBox': InstallBox,
  'InventoryGrid': InventoryGrid,
  'ItemSlot': ItemSlot,
  'JazariStateMachine': JazariStateMachine,
  'Label': LabelPattern,
  'LabelPattern': LabelPattern,
  'LandingPageTemplate': LandingPageTemplate,
  'LawReferenceTooltip': LawReferenceTooltip,
  'LearningCanvas': LearningCanvas,
  'Lightbox': Lightbox,
  'LikertScale': LikertScale,
  'LineChart': LineChart,
  'List': List,
  'LoadingState': LoadingState,
  'MapView': MapView,
  'MarkdownContent': MarkdownContent,
  'MarketingFooter': MarketingFooter,
  'MarketingStatCard': MarketingStatCard,
  'MasterDetail': MasterDetail,
  'MasterDetailLayout': MasterDetailLayout,
  'MathCanvas': MathCanvas,
  'MatrixQuestion': MatrixQuestion,
  'MediaGallery': MediaGallery,
  'Menu': Menu,
  'Meter': Meter,
  'MiniMap': MiniMap,
  'Modal': Modal,
  'ModalSlot': ModalSlot,
  'ModuleCard': ModuleCard,
  'Navigation': Navigation,
  'NumberStepper': NumberStepper,
  'ObjectRulePanel': ObjectRulePanel,
  'OptionConstraintGroup': OptionConstraintGroup,
  'OrbitalVisualization': OrbitalVisualization,
  'Overlay': Overlay,
  'PageHeader': PageHeader,
  'Pagination': Pagination,
  'PatternTile': PatternTile,
  'PhysicsCanvas': PhysicsCanvas,
  'Popover': Popover,
  'PositionedCanvas': PositionedCanvas,
  'PricingCard': PricingCard,
  'PricingGrid': PricingGrid,
  'PricingOrganism': PricingOrganism,
  'PricingPageTemplate': PricingPageTemplate,
  'ProgressBar': ProgressBar,
  'ProgressDots': ProgressDots,
  'PullQuote': PullQuote,
  'PullToRefresh': PullToRefresh,
  'QrScanner': QrScanner,
  'QuizBlock': QuizBlock,
  'Radio': Radio,
  'RangeSlider': RangeSlider,
  'ReflectionBlock': ReflectionBlock,
  'RelationSelect': RelationSelect,
  'RepeatableFormSection': RepeatableFormSection,
  'ReplyTree': ReplyTree,
  'ResourceBar': ResourceBar,
  'ResourceCounter': ResourceCounter,
  'RichBlockEditor': RichBlockEditor,
  'RuntimeDebugger': RuntimeDebugger,
  'ScaledDiagram': ScaledDiagram,
  'ScoreDisplay': ScoreDisplay,
  'SearchInput': SearchInput,
  'Section': Section,
  'SectionHeader': SectionHeader,
  'SegmentRenderer': SegmentRenderer,
  'Select': Select,
  'SequenceBar': SequenceBar,
  'ServiceCatalog': ServiceCatalog,
  'ShowcaseCard': ShowcaseCard,
  'ShowcaseOrganism': ShowcaseOrganism,
  'SidePanel': SidePanel,
  'Sidebar': Sidebar,
  'SignaturePad': SignaturePad,
  'SimpleGrid': SimpleGrid,
  'Skeleton': Skeleton,
  'SocialProof': SocialProof,
  'SortableList': SortableList,
  'Spacer': SpacerPattern,
  'SpacerPattern': SpacerPattern,
  'Sparkline': Sparkline,
  'Spinner': Spinner,
  'Split': Split,
  'SplitPane': SplitPane,
  'SplitSection': SplitSection,
  'Sprite': Sprite,
  'Stack': Stack,
  'StarRating': StarRating,
  'StatBadge': StatBadge,
  'StatCard': StatCard,
  'StatDisplay': StatDisplay,
  'StateGraph': StateGraph,
  'StateIndicator': StateIndicator,
  'StateJsonView': StateJsonView,
  'StateMachineView': StateMachineView,
  'StatsGrid': StatsGrid,
  'StatsOrganism': StatsOrganism,
  'StatusDot': StatusDot,
  'StatusEffect': StatusEffect,
  'StepFlow': StepFlow,
  'StepFlowOrganism': StepFlowOrganism,
  'SubagentTracePanel': SubagentTracePanel,
  'SvgBranch': SvgBranch,
  'SvgConnection': SvgConnection,
  'SvgFlow': SvgFlow,
  'SvgGrid': SvgGrid,
  'SvgLobe': SvgLobe,
  'SvgMesh': SvgMesh,
  'SvgMorph': SvgMorph,
  'SvgNode': SvgNode,
  'SvgPulse': SvgPulse,
  'SvgRing': SvgRing,
  'SvgShield': SvgShield,
  'SvgStack': SvgStack,
  'SwipeableRow': SwipeableRow,
  'Switch': Switch,
  'TabbedContainer': TabbedContainer,
  'TableView': TableView,
  'Tabs': Tabs,
  'TagCloud': TagCloud,
  'TagInput': TagInput,
  'TeamCard': TeamCard,
  'TeamOrganism': TeamOrganism,
  'TextHighlight': TextHighlight,
  'Textarea': Textarea,
  'ThemeToggle': ThemeToggle,
  'TimeSlotCell': TimeSlotCell,
  'Timeline': Timeline,
  'TimerDisplay': TimerDisplay,
  'Toast': Toast,
  'ToastSlot': ToastSlot,
  'Tooltip': Tooltip,
  'TraitFrame': TraitFrame,
  'TraitSlot': TraitSlot,
  'TrendIndicator': TrendIndicator,
  'TurnIndicator': TurnIndicator,
  'TypewriterText': TypewriterText,
  'Typography': Typography,
  'UISlotRenderer': UISlotRenderer,
  'UploadDropZone': UploadDropZone,
  'VStack': VStack,
  'VariablePanel': VariablePanel,
  'VersionDiff': VersionDiff,
  'ViolationAlert': ViolationAlert,
  'VoteStack': VoteStack,
  'WaypointMarker': WaypointMarker,
  'WizardContainer': WizardContainer,
  'WizardNavigation': WizardNavigation,
  'WizardProgress': WizardProgress,

  // Semantic aliases
  'Text': TextPattern,
};
